// Poker quiz/scenario data
// Revised baseline:
// - Standard no-limit Texas Hold'em cash-game strategy.
// - Assume 100bb effective stacks unless a scenario says otherwise.
// - Assume no antes and no tournament ICM pressure.
// - Preflop "Call" is only used when hero is facing prior action.
// - If hero is first in, default options should be Fold/Raise, not limp/call.

export const CASH_GAME_BASELINE = {
  game: "No-limit Texas Hold'em cash",
  tableDefault: "6-max unless stated",
  stackBB: 100,
  noAntes: true,
  note: "Use explicit action text for every preflop spot: folded to hero, facing an open, or facing a 3-bet.",
};


export const HAND_QUIZ = [
  {
    cards: [["A","♠"],["A","♥"],["A","♦"],["7","♣"],["3","♠"]],
    answer: "Three of a Kind",
    options: ["Three of a Kind", "Two Pair", "Full House", "Four of a Kind"],
    explain: "Three aces with no pair to make a full house. This is 'trips' (or a 'set' if your aces came from a pocket pair).",
  },
  {
    cards: [["K","♥"],["Q","♥"],["J","♥"],["10","♥"],["9","♥"]],
    answer: "Straight Flush",
    options: ["Royal Flush", "Straight Flush", "Flush", "Straight"],
    explain: "Five consecutive hearts — but it's not a Royal Flush because that requires A-K-Q-J-10 specifically.",
  },
  {
    cards: [["8","♠"],["8","♥"],["K","♦"],["K","♣"],["3","♠"]],
    answer: "Two Pair",
    options: ["Two Pair", "Three of a Kind", "Full House", "One Pair"],
    explain: "Kings and eights. You'd describe this as 'two pair, kings and eights' — the higher pair is named first.",
  },
  {
    cards: [["A","♣"],["K","♣"],["Q","♣"],["J","♣"],["10","♣"]],
    answer: "Royal Flush",
    options: ["Royal Flush", "Straight Flush", "Flush", "Five of a Kind"],
    explain: "The unbeatable hand. A-K-Q-J-10 of the same suit. You'll see one roughly once every 650,000 hands.",
  },
  {
    cards: [["7","♠"],["7","♥"],["7","♦"],["2","♣"],["2","♠"]],
    answer: "Full House",
    options: ["Full House", "Three of a Kind", "Two Pair", "Four of a Kind"],
    explain: "Three sevens plus a pair of twos. Spoken as 'sevens full of twos.' Ranked by the trips.",
  },
  {
    cards: [["5","♠"],["4","♥"],["3","♦"],["2","♣"],["A","♠"]],
    answer: "Straight",
    options: ["Straight", "Straight Flush", "High Card", "Flush"],
    explain: "The 'wheel' — A-2-3-4-5, where the ace plays low. It's the lowest possible straight.",
  },
  {
    cards: [["9","♣"],["9","♠"],["9","♥"],["9","♦"],["K","♣"]],
    answer: "Four of a Kind",
    options: ["Four of a Kind", "Full House", "Three of a Kind", "Straight Flush"],
    explain: "Quad nines with a king kicker. 'Quads' beat anything except a straight flush or royal flush.",
  },
  {
    cards: [["A","♥"],["10","♥"],["7","♥"],["4","♥"],["2","♥"]],
    answer: "Flush",
    options: ["Flush", "Straight Flush", "Royal Flush", "High Card"],
    explain: "Five hearts but not in sequence — that's a flush, ace-high. Beats any straight, loses to a full house.",
  },
  {
    cards: [["Q","♠"],["J","♥"],["10","♦"],["9","♣"],["8","♠"]],
    answer: "Straight",
    options: ["Straight", "Straight Flush", "High Card", "Three of a Kind"],
    explain: "Q-J-10-9-8, mixed suits. Queen-high straight. The suits being different is what makes it a straight rather than a straight flush.",
  },
  {
    cards: [["6","♠"],["6","♦"],["3","♣"],["3","♥"],["3","♠"]],
    answer: "Full House",
    options: ["Full House", "Two Pair", "Three of a Kind", "Four of a Kind"],
    explain: "Threes full of sixes. Note: it's named by the trips first ('threes full'), not by which pair is higher.",
  },
  {
    cards: [["A","♦"],["K","♥"],["Q","♠"],["10","♣"],["7","♦"]],
    answer: "High Card",
    options: ["High Card", "One Pair", "Straight", "Flush"],
    explain: "No pair, no straight (missing the jack), no flush. Ace-high. About a third of all dealt hands end up here.",
  },
  {
    cards: [["J","♣"],["J","♦"],["J","♠"],["A","♥"],["K","♦"]],
    answer: "Three of a Kind",
    options: ["Three of a Kind", "Two Pair", "Full House", "Straight"],
    explain: "Trip jacks with A-K kickers. Strong hand, but watch for full houses on paired boards.",
  },
  {
    cards: [["A","♠"],["A","♣"],["K","♥"],["K","♦"],["Q","♠"]],
    answer: "Two Pair",
    options: ["Two Pair", "Three of a Kind", "Full House", "Four of a Kind"],
    explain: "Aces and kings — the strongest two pair possible. Often called 'two pair, aces up.'",
  },
  {
    cards: [["10","♠"],["10","♥"],["6","♣"],["4","♦"],["2","♠"]],
    answer: "One Pair",
    options: ["One Pair", "Two Pair", "Three of a Kind", "High Card"],
    explain: "Pair of tens with junk kickers. A common holding — often the winner in unpaired-board pots.",
  },
  {
    cards: [["A","♣"],["2","♣"],["3","♣"],["4","♣"],["5","♣"]],
    answer: "Straight Flush",
    options: ["Straight Flush", "Royal Flush", "Flush", "Straight"],
    explain: "The 'steel wheel' — 5-high straight flush. Lowest straight flush possible, but still crushes regular flushes.",
  },
  {
    cards: [["K","♠"],["K","♣"],["K","♥"],["K","♦"],["A","♠"]],
    answer: "Four of a Kind",
    options: ["Four of a Kind", "Full House", "Royal Flush", "Three of a Kind"],
    explain: "Quad kings with the ace kicker. Only quad aces and any straight/royal flush beat this.",
  },
  {
    cards: [["7","♥"],["6","♥"],["5","♣"],["4","♦"],["3","♠"]],
    answer: "Straight",
    options: ["Straight", "Straight Flush", "Flush", "High Card"],
    explain: "7-6-5-4-3 with mixed suits. Seven-high straight. Don't be fooled by the two hearts — flushes need five of a suit.",
  },
  {
    cards: [["Q","♦"],["Q","♥"],["Q","♣"],["Q","♠"],["3","♥"]],
    answer: "Four of a Kind",
    options: ["Four of a Kind", "Full House", "Three of a Kind", "Straight Flush"],
    explain: "Quad queens. The kicker (3) only matters if another player also has quad queens — which can't happen with the same four cards in a community-card game, but matters in stud-style games.",
  },
  {
    cards: [["8","♦"],["6","♦"],["4","♦"],["2","♦"],["A","♦"]],
    answer: "Flush",
    options: ["Flush", "Straight Flush", "Two Pair", "High Card"],
    explain: "Five diamonds, ace-high. Not a straight (gaps everywhere), but a strong flush. Note that it's not a 'royal flush' — that requires A-K-Q-J-10 specifically.",
  },
  {
    cards: [["5","♣"],["5","♦"],["5","♥"],["8","♠"],["8","♣"]],
    answer: "Full House",
    options: ["Full House", "Three of a Kind", "Two Pair", "Four of a Kind"],
    explain: "Fives full of eights. Even though the eights are higher, the trips determine the rank — 5s full beats any 4s full but loses to any 6s full.",
  },
  {
    cards: [["K","♠"],["K","♥"],["Q","♦"],["Q","♣"],["9","♠"]],
    answer: "Two Pair",
    options: ["Two Pair", "Three of a Kind", "Full House", "One Pair"],
    explain: "Kings and queens with a nine kicker. 'Kings up' — strong two pair but loses to any set on this layout.",
  },
  {
    cards: [["J","♥"],["J","♣"],["10","♦"],["9","♠"],["8","♥"]],
    answer: "One Pair",
    options: ["One Pair", "Straight", "Two Pair", "Three of a Kind"],
    explain: "Pair of jacks. Don't be fooled by the connectors — 10-9-8 plus a J isn't a straight without a 7 or Q. You'd need J-10-9-8-7 or Q-J-10-9-8.",
  },
  {
    cards: [["A","♦"],["K","♣"],["Q","♥"],["J","♠"],["9","♦"]],
    answer: "High Card",
    options: ["High Card", "Straight", "One Pair", "Flush"],
    explain: "Ace-high. Missing the ten kills the straight (A-K-Q-J-10). One gap and all that broadway is just five high cards.",
  },
  {
    cards: [["9","♠"],["9","♥"],["9","♦"],["A","♣"],["K","♠"]],
    answer: "Three of a Kind",
    options: ["Three of a Kind", "Two Pair", "Full House", "Straight"],
    explain: "Trip nines with ace-king kickers. 'Trips' if the third nine came from the board, a 'set' if both nines came from your pocket pair.",
  },
  {
    cards: [["10","♥"],["J","♥"],["Q","♥"],["K","♥"],["A","♥"]],
    answer: "Royal Flush",
    options: ["Royal Flush", "Straight Flush", "Flush", "Straight"],
    explain: "The royal — A-K-Q-J-10 of hearts. The strongest possible hand. Anything else is second place.",
  },
  {
    cards: [["6","♣"],["6","♦"],["6","♥"],["6","♠"],["2","♣"]],
    answer: "Four of a Kind",
    options: ["Four of a Kind", "Full House", "Three of a Kind", "Straight Flush"],
    explain: "Quad sixes with a two kicker. Only quads with a bigger kicker (or higher quads) beats this in a community-card game.",
  },
  {
    cards: [["5","♥"],["5","♦"],["2","♠"],["2","♣"],["A","♦"]],
    answer: "Two Pair",
    options: ["Two Pair", "One Pair", "Three of a Kind", "Full House"],
    explain: "Fives and twos with an ace kicker. A weak two pair — vulnerable to any higher two pair or a single overpair holding.",
  },
  {
    cards: [["7","♠"],["6","♠"],["5","♠"],["4","♠"],["3","♠"]],
    answer: "Straight Flush",
    options: ["Straight Flush", "Royal Flush", "Flush", "Straight"],
    explain: "7-high straight flush — five spades in a row, 3 through 7. Loses only to higher straight flushes and royals.",
  },
  {
    cards: [["8","♥"],["8","♦"],["3","♣"],["3","♠"],["3","♥"]],
    answer: "Full House",
    options: ["Full House", "Two Pair", "Three of a Kind", "Four of a Kind"],
    explain: "Threes full of eights. Always named by the trips first — '3s full,' not '8s and 3s.'",
  },
  {
    cards: [["K","♠"],["K","♣"],["K","♥"],["A","♦"],["A","♣"]],
    answer: "Full House",
    options: ["Full House", "Two Pair", "Three of a Kind", "Four of a Kind"],
    explain: "Kings full of aces. Higher trips wins the boat war — even when the pair is aces, the trips rank the hand.",
  },
  {
    cards: [["9","♦"],["8","♦"],["7","♦"],["6","♦"],["5","♦"]],
    answer: "Straight Flush",
    options: ["Straight Flush", "Royal Flush", "Flush", "Straight"],
    explain: "9-high straight flush in diamonds. Anything between '5-high' (the steel wheel) and 'K-high' is just a straight flush — the royal label is reserved for A-K-Q-J-10.",
  },
  {
    cards: [["4","♣"],["4","♦"],["4","♥"],["7","♠"],["2","♣"]],
    answer: "Three of a Kind",
    options: ["Three of a Kind", "Two Pair", "Full House", "One Pair"],
    explain: "Trip fours with junk kickers. Strong on uncoordinated boards; very vulnerable on connected ones.",
  },
  {
    cards: [["2","♣"],["2","♦"],["2","♥"],["2","♠"],["7","♥"]],
    answer: "Four of a Kind",
    options: ["Four of a Kind", "Full House", "Three of a Kind", "Two Pair"],
    explain: "Quad deuces with a seven kicker. Yes — quad twos beats every full house and every flush. Rank goes by category, not card value.",
  },
  {
    cards: [["A","♥"],["K","♥"],["Q","♥"],["9","♥"],["5","♥"]],
    answer: "Flush",
    options: ["Flush", "Royal Flush", "Straight Flush", "Straight"],
    explain: "Ace-high flush. Missing the J and 10 means it's just a flush, not a royal. Still strong — beats any straight.",
  },
  {
    cards: [["A","♣"],["K","♥"],["Q","♠"],["J","♦"],["10","♣"]],
    answer: "Straight",
    options: ["Straight", "Straight Flush", "Royal Flush", "Flush"],
    explain: "Broadway — the highest straight, A-K-Q-J-10 with mixed suits. The royal flush is this same straight in one suit; mixed suits just makes it a straight.",
  },
  {
    cards: [["6","♥"],["5","♣"],["4","♦"],["3","♠"],["2","♥"]],
    answer: "Straight",
    options: ["Straight", "High Card", "Straight Flush", "One Pair"],
    explain: "6-high straight, mixed suits. One step above the wheel.",
  },
  {
    cards: [["Q","♦"],["Q","♥"],["7","♣"],["5","♠"],["2","♦"]],
    answer: "One Pair",
    options: ["One Pair", "Two Pair", "Three of a Kind", "High Card"],
    explain: "Pair of queens with 7-5-2 kickers. Very common holding — wins a lot of small pots, loses big ones to sets and two pair.",
  },
  {
    cards: [["A","♠"],["K","♠"],["7","♦"],["4","♣"],["2","♥"]],
    answer: "High Card",
    options: ["High Card", "One Pair", "Flush", "Straight"],
    explain: "Ace-king high. The two spades aren't enough for a flush — you need five of a suit. No pair, no straight.",
  },
  {
    cards: [["10","♣"],["10","♠"],["10","♦"],["10","♥"],["A","♣"]],
    answer: "Four of a Kind",
    options: ["Four of a Kind", "Full House", "Royal Flush", "Three of a Kind"],
    explain: "Quad tens with the ace kicker. Only quad jacks, quad queens, quad kings, and quad aces beat this — plus straight flushes and the royal.",
  },
  {
    cards: [["J","♠"],["J","♦"],["J","♥"],["4","♣"],["4","♠"]],
    answer: "Full House",
    options: ["Full House", "Three of a Kind", "Two Pair", "Four of a Kind"],
    explain: "Jacks full of fours. A premium boat — only queens-full and up beats it on this layout.",
  },
  {
    cards: [["8","♣"],["7","♥"],["6","♦"],["5","♠"],["4","♣"]],
    answer: "Straight",
    options: ["Straight", "Straight Flush", "Flush", "High Card"],
    explain: "8-high straight. Mixed suits — no flush, no straight flush.",
  },
  {
    cards: [["A","♦"],["A","♥"],["7","♣"],["7","♠"],["3","♦"]],
    answer: "Two Pair",
    options: ["Two Pair", "Three of a Kind", "Full House", "One Pair"],
    explain: "Aces and sevens — 'aces up.' Strong two pair, but watch out for any set on the board.",
  },
  {
    cards: [["8","♠"],["8","♣"],["8","♥"],["8","♦"],["3","♠"]],
    answer: "Four of a Kind",
    options: ["Four of a Kind", "Full House", "Straight Flush", "Three of a Kind"],
    explain: "Quad eights with a three kicker. The kicker only matters in stud-type games; in community-card games the four eights are the four eights.",
  },
  {
    cards: [["K","♣"],["Q","♥"],["J","♣"],["10","♦"],["9","♠"]],
    answer: "Straight",
    options: ["Straight", "Straight Flush", "Flush", "High Card"],
    explain: "King-high straight, K-Q-J-10-9. Mixed suits — close to the nuts but anyone with an ace makes Broadway.",
  },
  {
    cards: [["7","♥"],["7","♦"],["5","♣"],["5","♠"],["3","♥"]],
    answer: "Two Pair",
    options: ["Two Pair", "One Pair", "Three of a Kind", "Full House"],
    explain: "Sevens and fives with a three kicker. A weak-ish two pair — many higher two pair combinations dominate it.",
  },
  {
    cards: [["A","♠"],["A","♣"],["A","♥"],["K","♦"],["K","♣"]],
    answer: "Full House",
    options: ["Full House", "Three of a Kind", "Four of a Kind", "Two Pair"],
    explain: "Aces full of kings — the highest non-quads full house. Often called 'aces full.' Loses only to quads and straight flushes.",
  },
  {
    cards: [["9","♥"],["8","♥"],["6","♥"],["3","♥"],["2","♥"]],
    answer: "Flush",
    options: ["Flush", "Straight Flush", "Straight", "High Card"],
    explain: "Nine-high flush. The hearts are not consecutive — 9-8-6-3-2 is just a flush, not a straight flush.",
  },
  {
    cards: [["6","♦"],["6","♥"],["6","♣"],["A","♠"],["2","♦"]],
    answer: "Three of a Kind",
    options: ["Three of a Kind", "Two Pair", "Full House", "One Pair"],
    explain: "Trip sixes, ace-deuce kickers. Hidden middle set — devastating against opponents who think their top pair is good.",
  },
  {
    cards: [["3","♠"],["3","♣"],["A","♥"],["A","♦"],["A","♠"]],
    answer: "Full House",
    options: ["Full House", "Three of a Kind", "Two Pair", "Four of a Kind"],
    explain: "Aces full of threes. The trips are aces, so this is named 'aces full' — the second-strongest non-quad hand.",
  },
  {
    cards: [["Q","♠"],["J","♣"],["9","♦"],["6","♥"],["3","♠"]],
    answer: "High Card",
    options: ["High Card", "One Pair", "Straight", "Flush"],
    explain: "Queen-high. Five disconnected cards with no pair, no flush draw five-of-a-suit, no straight. Bottom of the pack.",
  },
];

export const WINNING_HAND_QUIZ = [
  {
    flop: [["K","♠"],["7","♦"],["2","♣"]],
    turn: ["3","♠"], river: ["J","♥"],
    handA: [["A","♥"],["K","♣"]],
    handB: [["7","♥"],["7","♣"]],
    explain: "A flopped set rarely loses. Sevens hit a set on the flop and the runout was bricks — no straight or flush gets there. Top pair top kicker pays off the whole way.",
  },
  {
    flop: [["Q","♥"],["J","♥"],["10","♥"]],
    turn: ["2","♣"], river: ["5","♦"],
    handA: [["A","♥"],["K","♣"]],
    handB: [["9","♥"],["8","♣"]],
    explain: "Both made straights on the flop — A-K-Q-J-10 (Broadway) vs Q-J-10-9-8. The higher straight wins. Note Hand A also has the Ace of hearts, but with only three hearts on the board, no flush is possible.",
  },
  {
    flop: [["A","♠"],["A","♥"],["K","♦"]],
    turn: ["3","♣"], river: ["7","♦"],
    handA: [["A","♣"],["Q","♥"]],
    handB: [["K","♠"],["K","♣"]],
    explain: "Pocket kings turned into kings full of aces — beating trip aces with a queen kicker. When the board has two pairs available (or a pair plus your set), the full house emerges. Boat beats trips.",
  },
  {
    flop: [["9","♣"],["8","♣"],["2","♣"]],
    turn: ["K","♥"], river: ["4","♦"],
    handA: [["A","♣"],["5","♦"]],
    handB: [["10","♥"],["7","♥"]],
    explain: "The nut flush was made on the flop — Hand A had one club and the board brought three. Hand B had open-ended straight outs but the turn (K) and river (4) bricked. Made hands beat broken draws every time.",
  },
  {
    flop: [["Q","♦"],["Q","♣"],["5","♥"]],
    turn: ["8","♠"], river: ["3","♦"],
    handA: [["Q","♥"],["5","♠"]],
    handB: [["A","♥"],["A","♣"]],
    explain: "The board paired queens, and Hand A had Q-5 — flopping queens full of fives. Pocket aces flopped two pair (aces and queens) but never improved. The full house wins. Aces aren't invincible on paired boards.",
  },
  {
    flop: [["J","♠"],["J","♦"],["J","♣"]],
    turn: ["7","♥"], river: ["2","♣"],
    handA: [["A","♥"],["K","♥"]],
    handB: [["10","♣"],["10","♦"]],
    explain: "Trips on the board makes any pocket pair into a full house. Pocket tens become jacks-full-of-tens — beating trip jacks with the A-K kicker. When the board shows three of a kind, every pocket pair is gold.",
  },
  {
    flop: [["8","♥"],["7","♠"],["6","♦"]],
    turn: ["A","♠"], river: ["K","♦"],
    handA: [["9","♣"],["5","♦"]],
    handB: [["10","♥"],["9","♥"]],
    explain: "Both flopped straights. Hand A: 9-8-7-6-5. Hand B: 10-9-8-7-6. Higher straight wins. The turn and river were bricks — neither helped or hurt.",
  },
  {
    flop: [["K","♥"],["10","♥"],["3","♣"]],
    turn: ["7","♦"], river: ["2","♠"],
    handA: [["K","♣"],["Q","♦"]],
    handB: [["10","♣"],["10","♦"]],
    explain: "Top pair top kicker vs a flopped set. The runout was dry — no flush, no straight to bail Hand A out. Sets are the silent killers of poker; opponents almost never see them coming.",
  },
  {
    flop: [["A","♠"],["K","♠"],["Q","♠"]],
    turn: ["7","♦"], river: ["3","♣"],
    handA: [["J","♠"],["10","♠"]],
    handB: [["A","♥"],["A","♦"]],
    explain: "Royal flush vs trip aces. The flop already had it locked — A-K-Q-J-10 of spades. Trip aces is a hand most players go broke with; here, against the ultimate hand, it's drawing dead from the flop.",
  },
  {
    flop: [["6","♦"],["6","♥"],["6","♣"]],
    turn: ["A","♠"], river: ["K","♥"],
    handA: [["A","♥"],["A","♦"]],
    handB: [["6","♠"],["2","♣"]],
    explain: "Quad sixes vs aces full. The board flopped trip sixes — a wild flop. The case six in Hand B made quads. Hand A turned aces full but quads still win. Note: if Hand B held T-2 instead, quads would still win on the strength of the four sixes.",
  },
  {
    flop: [["7","♥"],["5","♦"],["3","♠"]],
    turn: ["K","♣"], river: ["2","♦"],
    handA: [["A","♣"],["A","♥"]],
    handB: [["6","♦"],["4","♣"]],
    explain: "Pocket aces flopped an overpair. Hand B flopped a 7-high straight (7-6-5-4-3) — already ahead. The turn and river didn't pair the board, so no full house redemption for A. Read texture; small connected boards crush overpairs.",
  },
  {
    flop: [["10","♣"],["9","♣"],["8","♣"]],
    turn: ["2","♦"], river: ["K","♠"],
    handA: [["J","♣"],["7","♣"]],
    handB: [["A","♣"],["K","♦"]],
    explain: "Hand A flopped a straight flush — J-10-9-8-7 of clubs. Hand B had the nut flush draw with the Ace of clubs but only ever had four clubs. The river K paired top but it didn't matter — straight flush is a near-unbeatable hand.",
  },
  {
    flop: [["A","♠"],["K","♥"],["7","♦"]],
    turn: ["4","♣"], river: ["2","♠"],
    handA: [["A","♣"],["J","♥"]],
    handB: [["A","♦"],["10","♦"]],
    explain: "Both have aces with a king playing from the board, so it comes down to kicker. Jack outranks ten. The runout never paired or made anyone two pair, so kickers decide it. This is exactly why Ace-Jack vs Ace-Ten matters.",
  },
  {
    flop: [["Q","♠"],["Q","♥"],["7","♦"]],
    turn: ["3","♣"], river: ["8","♥"],
    handA: [["Q","♦"],["A","♣"]],
    handB: [["7","♥"],["7","♣"]],
    explain: "Trips with the ace kicker vs a flopped underset that became sevens-full-of-queens. The board paired queens, the underpair pair makes the full house. Set-on-paired-board crushes trips every time.",
  },
  {
    flop: [["8","♥"],["8","♦"],["3","♣"]],
    turn: ["10","♦"], river: ["K","♠"],
    handA: [["A","♠"],["8","♣"]],
    handB: [["3","♥"],["3","♠"]],
    explain: "Trips with ace kicker vs underset that boats up. Threes full of eights wins. Notice both players were ahead of pocket aces here — paired-board flops with multiple players in is a classic trap for overpairs.",
  },
  {
    flop: [["K","♦"],["K","♠"],["K","♥"]],
    turn: ["A","♣"], river: ["2","♥"],
    handA: [["A","♦"],["K","♣"]],
    handB: [["A","♥"],["A","♠"]],
    explain: "Quad kings vs aces full of kings. Both monsters. The case king + ace makes quads. Pocket aces fill up to the second-best full house... and lose. This is the kind of hand that defines a player's career.",
  },
  {
    flop: [["J","♥"],["J","♠"],["6","♦"]],
    turn: ["8","♣"], river: ["6","♣"],
    handA: [["A","♣"],["J","♦"]],
    handB: [["6","♥"],["8","♥"]],
    explain: "Hand A had trip jacks the whole way. Hand B had bottom pair on the flop, then turned middle pair (8s and 6s), then RIVERED 6s full of jacks. The river card was a one-outer for the boat. Brutal.",
  },
  {
    flop: [["A","♥"],["10","♥"],["5","♣"]],
    turn: ["K","♥"], river: ["2","♥"],
    handA: [["A","♣"],["A","♠"]],
    handB: [["7","♥"],["6","♥"]],
    explain: "Pocket aces flopped a set of aces — looks unbeatable. But four hearts came on the board (Ah, Th, Kh, 2h), and Hand B has 7h-6h. With six total hearts available, Hand B plays the five highest: Ah-Kh-Th-7h-6h — an ace-high flush (using the board's Ah). Set of aces loses to a four-flush board when you don't hold the right suit.",
  },
  {
    flop: [["9","♥"],["8","♥"],["2","♦"]],
    turn: ["7","♥"], river: ["6","♥"],
    handA: [["A","♥"],["K","♦"]],
    handB: [["10","♣"],["9","♣"]],
    explain: "The runout brings four hearts. Hand A has the Ace of hearts — playing the nut flush. Hand B has 10-9-8-7-6, a ten-high straight from their pocket ten + the board. Flush beats straight. Hand A wins with ace-high flush.",
  },
  {
    flop: [["K","♥"],["Q","♦"],["3","♠"]],
    turn: ["J","♣"], river: ["10","♥"],
    handA: [["A","♥"],["A","♠"]],
    handB: [["9","♣"],["9","♦"]],
    explain: "Pocket aces and pocket nines both started as overpair / underpair. The board ran out K-Q-J-10 — meaning anyone with an Ace makes Broadway (A-K-Q-J-10), and anyone with a 9 makes a 9-high straight. Hand A's ace plays as A-K-Q-J-10. Hand B plays K-Q-J-10-9. Both straights, but Hand A's Broadway is the nuts.",
  },
  {
    flop: [["7","♣"],["7","♦"],["2","♥"]],
    turn: ["A","♠"], river: ["A","♣"],
    handA: [["A","♥"],["K","♥"]],
    handB: [["7","♥"],["7","♠"]],
    explain: "Quads vs aces full! The board double-paired (sevens flop, aces turn+river). Hand B had pocket sevens — quad sevens by the river. Hand A turned trip aces, rivered four-of-a-kind on the board... wait, with one ace in hand and two on the board plus the trips on the board, that's a full house: aces full of sevens. Quads still win.",
  },
  {
    flop: [["10","♠"],["10","♥"],["10","♦"]],
    turn: ["K","♠"], river: ["K","♦"],
    handA: [["K","♣"],["Q","♥"]],
    handB: [["A","♠"],["J","♠"]],
    explain: "The board ran out 10-10-10-K-K — already a full house by itself (tens full of kings). Hand A has K-Q: combining with the trip tens and the board kings makes K-K-K-10-10, kings full of tens. Hand B's A-J doesn't pair anything on the board, so they just play the board (10-10-10-K-K) — tens full of kings. Higher trips in the boat wins. Hand A by a single card.",
  },
  {
    flop: [["Q","♥"],["Q","♦"],["5","♣"]],
    turn: ["5","♥"], river: ["A","♠"],
    handA: [["A","♣"],["Q","♣"]],
    handB: [["A","♥"],["5","♦"]],
    explain: "Hand A flopped trip queens with the ace kicker. The river paired aces — but Hand A holds Ac! That makes Q-Q-Q-A-A: queens full of aces. Hand B (A-5) had two pair (As and 5s) on the river, but their best full house option is 5-5-5-A-A (using the trip 5s once the turn paired). Both players have a boat 'full of aces,' but queens-full beats fives-full. Higher trips wins the boat war.",
  },
  {
    flop: [["8","♠"],["7","♠"],["6","♠"]],
    turn: ["5","♠"], river: ["9","♠"],
    handA: [["A","♠"],["2","♥"]],
    handB: [["10","♠"],["J","♣"]],
    explain: "The board is five spades in sequence: 9-8-7-6-5 — already a straight flush. Both players play the board for at least a 9-high straight flush. Hand B has the 10 of spades, which extends the straight flush to 10-high (10-9-8-7-6). Hand A's Ace of spades doesn't help — A-2 leaves a gap, so A is stuck with the board's 9-high straight flush. Higher straight flush wins.",
  },
  {
    flop: [["A","♥"],["K","♥"],["Q","♣"]],
    turn: ["10","♣"], river: ["J","♦"],
    handA: [["10","♥"],["10","♦"]],
    handB: [["9","♣"],["8","♣"]],
    explain: "The river J completes Broadway on the board (A-K-Q-J-10). Hand A had a set of tens through the turn, then plays the board for Broadway on the river (the set is irrelevant — A-K-Q-J-10 is higher). Hand B's 9-8 makes nothing — they play A-K-Q-J-10 from the board. Both players play the board for Broadway: it's a chopped pot. TIE!",
    isTie: true,
  },
  {
    flop: [["6","♦"],["7","♥"],["8","♠"]],
    turn: ["9","♣"], river: ["10","♥"],
    handA: [["5","♣"],["4","♦"]],
    handB: [["J","♠"],["2","♣"]],
    explain: "The board itself contains 6-7-8-9-10 — a 10-high straight. Hand A's 5-4 doesn't play (their 6-7-8-9-10 straight is just the board; no improvement). Hand B's Jack makes J-10-9-8-7 — Jack-high straight. J-high beats 10-high. Hand B wins with the higher straight using just one card.",
  },
  {
    flop: [["9","♦"],["6","♠"],["2","♣"]],
    turn: ["J","♥"], river: ["4","♦"],
    handA: [["9","♣"],["9","♥"]],
    handB: [["A","♠"],["A","♣"]],
    explain: "Set of nines flopped, ran out clean. Hand B's overpair never improved and the board never paired. Bottom set quietly crushes overpairs on dry boards.",
  },
  {
    flop: [["K","♥"],["7","♥"],["3","♥"]],
    turn: ["2","♥"], river: ["9","♣"],
    handA: [["A","♥"],["8","♦"]],
    handB: [["Q","♥"],["10","♦"]],
    explain: "Four hearts came on the board. Both players have one heart in hand — both make flushes. Higher card in the flush wins: Hand A's Ace of hearts plays as an ace-high flush; Hand B's Queen is just a Q-high flush. Ace-high flush wins.",
  },
  {
    flop: [["5","♣"],["4","♦"],["3","♠"]],
    turn: ["2","♥"], river: ["K","♣"],
    handA: [["A","♥"],["Q","♠"]],
    handB: [["7","♣"],["6","♦"]],
    explain: "Hand A made the wheel — A-2-3-4-5 with the ace playing low. Hand B made a 7-high straight (7-6-5-4-3). The 7-high beats the wheel, which is the lowest possible straight. Hand B wins.",
  },
  {
    flop: [["J","♠"],["9","♠"],["8","♣"]],
    turn: ["10","♠"], river: ["4","♦"],
    handA: [["A","♠"],["5","♠"]],
    handB: [["Q","♣"],["7","♦"]],
    explain: "Hand A has the nut flush — A-J-10-9-5 of spades using both spades from hand plus three on the board. Hand B made a Queen-high straight (Q-J-10-9-8). Flush beats straight every time. Ace-high flush wins.",
  },
  {
    flop: [["K","♣"],["8","♦"],["4","♥"]],
    turn: ["5","♠"], river: ["J","♣"],
    handA: [["A","♦"],["K","♥"]],
    handB: [["K","♠"],["Q","♦"]],
    explain: "Both players flopped top pair of kings. The kicker decides: Ace outranks Queen. This is the textbook example of why kicker matters — A-K and K-Q look similar preflop but play very differently when a king flops.",
  },
  {
    flop: [["10","♥"],["9","♠"],["8","♦"]],
    turn: ["7","♣"], river: ["J","♥"],
    handA: [["A","♣"],["5","♥"]],
    handB: [["3","♦"],["2","♠"]],
    explain: "The board itself contains a Jack-high straight (J-10-9-8-7). Neither player has a card that improves on that straight. Both play J-10-9-8-7 from the board. It's a chop pot.",
    isTie: true,
  },
  {
    flop: [["8","♣"],["5","♠"],["2","♦"]],
    turn: ["K","♥"], river: ["4","♣"],
    handA: [["8","♠"],["8","♥"]],
    handB: [["5","♥"],["5","♦"]],
    explain: "Top set vs bottom set. Hand A has trip eights; Hand B has trip fives. Higher set wins, and there's no straight or flush available to bail out the loser. Sets-over-sets is one of the most expensive coolers in poker.",
  },
  {
    flop: [["7","♥"],["6","♣"],["5","♦"]],
    turn: ["K","♠"], river: ["2","♣"],
    handA: [["9","♠"],["8","♥"]],
    handB: [["K","♦"],["7","♦"]],
    explain: "Hand A flopped a 9-high straight (9-8-7-6-5). Hand B turned two pair (kings and sevens) but a straight always beats two pair. The river didn't pair the board, so no full-house redemption. Straight wins.",
  },
  {
    flop: [["A","♥"],["A","♣"],["7","♥"]],
    turn: ["A","♦"], river: ["8","♥"],
    handA: [["A","♠"],["Q","♣"]],
    handB: [["J","♥"],["10","♥"]],
    explain: "Hand A makes quad aces — three on the board (A♥, A♣, A♦) plus the A♠ in hand. Hand B makes an ace-high flush using the board's hearts (A♥, 7♥, 8♥) plus J♥ and 10♥ from hand. Quads beat any flush. Hand A wins.",
  },
  {
    flop: [["Q","♠"],["Q","♥"],["5","♦"]],
    turn: ["K","♣"], river: ["5","♣"],
    handA: [["K","♦"],["K","♥"]],
    handB: [["Q","♣"],["J","♠"]],
    explain: "Hand A makes kings full of queens (KKK + QQ on board). Hand B makes queens full of fives (QQQ + 55 on board). Both have full houses, but the player with the higher trips wins. Kings full beats queens full.",
  },
  {
    flop: [["A","♣"],["8","♦"],["5","♥"]],
    turn: ["A","♦"], river: ["K","♠"],
    handA: [["K","♥"],["Q","♥"]],
    handB: [["8","♣"],["6","♣"]],
    explain: "The board paired aces on the turn. Hand A makes two pair, aces and kings. Hand B makes two pair, aces and eights. Both share the aces; the second pair decides — kings beat eights. Hand A wins.",
  },
  {
    flop: [["J","♠"],["J","♣"],["9","♥"]],
    turn: ["4","♦"], river: ["2","♠"],
    handA: [["A","♥"],["J","♦"]],
    handB: [["9","♠"],["9","♣"]],
    explain: "Hand A flopped trip jacks with the ace kicker. Hand B flopped bottom set (nines) and turned it into nines full of jacks once you read the board correctly — three 9s with the paired jacks counts as 9-9-9-J-J. Boat beats trips. Underset boats up.",
  },
  {
    flop: [["9","♥"],["6","♥"],["2","♥"]],
    turn: ["3","♥"], river: ["8","♣"],
    handA: [["A","♥"],["5","♣"]],
    handB: [["K","♥"],["4","♣"]],
    explain: "Four hearts on the board, and both players have one heart in hand. Hand A makes an ace-high flush; Hand B makes a king-high flush. Highest card in the flush wins. The Ace of hearts is the nut blocker — exactly why suited aces have so much value.",
  },
  {
    flop: [["10","♣"],["8","♠"],["5","♥"]],
    turn: ["9","♣"], river: ["J","♦"],
    handA: [["J","♣"],["10","♦"]],
    handB: [["Q","♥"],["7","♠"]],
    explain: "Hand A turned/rivered top two pair (jacks and tens). Hand B's seven made a Queen-high straight by the river: Q-J-10-9-8. Straight beats two pair. Connected boards make two-pair hands very vulnerable.",
  },
  {
    flop: [["Q","♥"],["8","♦"],["3","♠"]],
    turn: ["4","♣"], river: ["2","♥"],
    handA: [["A","♣"],["Q","♠"]],
    handB: [["8","♥"],["7","♥"]],
    explain: "Hand A has top pair (queens) with the ace kicker. Hand B has middle pair (eights). Top pair always beats middle pair when there's no other improvement. Queens with A kicker wins.",
  },
  {
    flop: [["7","♦"],["6","♦"],["4","♦"]],
    turn: ["5","♦"], river: ["K","♣"],
    handA: [["3","♦"],["8","♥"]],
    handB: [["A","♦"],["K","♦"]],
    explain: "Four diamonds on the board. Hand A has the 3 of diamonds, completing 7-6-5-4-3 of diamonds — a 7-high straight flush. Hand B has the Ace of diamonds, making an ace-high flush. Straight flush beats flush, even nut flush. Hand A wins a brutal cooler.",
  },
  {
    flop: [["7","♣"],["4","♠"],["2","♦"]],
    turn: ["9","♦"], river: ["8","♥"],
    handA: [["K","♣"],["K","♠"]],
    handB: [["J","♥"],["J","♦"]],
    explain: "Both have overpairs that never improved. Kings outrank jacks. When neither pair improves and no straight or flush is available, the higher pocket pair wins.",
  },
  {
    flop: [["K","♦"],["8","♥"],["3","♣"]],
    turn: ["J","♣"], river: ["8","♣"],
    handA: [["K","♠"],["Q","♦"]],
    handB: [["8","♦"],["8","♠"]],
    explain: "Hand B flopped a set of eights and rivered quads — the case eight. Hand A had top pair plus the river-rivered two pair (kings and eights), but quads always wins. A textbook one-outer scenario.",
  },
  {
    flop: [["A","♠"],["7","♠"],["3","♣"]],
    turn: ["9","♠"], river: ["4","♠"],
    handA: [["K","♠"],["Q","♥"]],
    handB: [["J","♦"],["10","♦"]],
    explain: "Four spades came on the board. Hand A has the King of spades — making an ace-high flush using the board's ace (the highest five spades are A-K-9-7-4). Hand B has no spade and no pair — they just play A-J-10-9-7 high card from the board. Flush easily wins.",
  },
  {
    flop: [["6","♣"],["7","♦"],["J","♥"]],
    turn: ["9","♠"], river: ["8","♥"],
    handA: [["10","♣"],["4","♥"]],
    handB: [["A","♣"],["A","♠"]],
    explain: "Hand A's ten makes a 10-high straight (10-9-8-7-6) on the river. Hand B's pocket aces never improved. Even premium overpairs lose when the board runs out connected. Always re-read the board after the river.",
  },
  {
    flop: [["Q","♥"],["9","♣"],["8","♦"]],
    turn: ["10","♠"], river: ["2","♣"],
    handA: [["Q","♠"],["Q","♦"]],
    handB: [["J","♥"],["7","♦"]],
    explain: "Hand A has a set of queens. Hand B made a jack-high straight (J-10-9-8-7) by the turn. Straight beats set. This is why sets on coordinated boards are dangerous — protect aggressively before draws complete.",
  },
  {
    flop: [["K","♣"],["5","♥"],["3","♦"]],
    turn: ["7","♠"], river: ["9","♦"],
    handA: [["A","♥"],["K","♦"]],
    handB: [["A","♣"],["Q","♠"]],
    explain: "Hand A has top pair (kings) with the ace kicker. Hand B never paired — they have ace-high. Any pair beats any high card. Hand A wins by a wide margin.",
  },
  {
    flop: [["A","♦"],["9","♠"],["7","♣"]],
    turn: ["9","♥"], river: ["3","♠"],
    handA: [["A","♣"],["K","♥"]],
    handB: [["9","♦"],["7","♥"]],
    explain: "Hand A has two pair (aces and nines, K kicker). Hand B has nines full of sevens — they flopped two pair (9s and 7s) and the turn paired the 9 to give them three nines plus the pair of sevens. Boat beats two pair. Underset / two-pair traps are real.",
  },
  {
    flop: [["5","♣"],["4","♥"],["3","♠"]],
    turn: ["2","♦"], river: ["A","♠"],
    handA: [["K","♦"],["Q","♣"]],
    handB: [["9","♣"],["8","♥"]],
    explain: "The full board reads 5-4-3-2-A — a wheel straight already there for everyone. Neither player has a card that extends the straight. Both play A-2-3-4-5 from the board. Chop pot.",
    isTie: true,
  },
  {
    flop: [["K","♠"],["J","♥"],["4","♦"]],
    turn: ["9","♣"], river: ["6","♥"],
    handA: [["A","♠"],["K","♥"]],
    handB: [["A","♥"],["5","♥"]],
    explain: "Hand A has top pair top kicker (kings, ace kicker). Hand B was on a busted heart flush draw — only four hearts came across the board and their hand. No flush, no pair. Hand B has ace-high. Top pair wins easily.",
  },
  {
    flop: [["Q","♦"],["7","♣"],["4","♠"]],
    turn: ["J","♥"], river: ["3","♣"],
    handA: [["Q","♣"],["K","♠"]],
    handB: [["Q","♥"],["J","♦"]],
    explain: "Both players flopped top pair of queens. Hand B turned two pair (queens and jacks). Hand A still has just top pair with a K kicker. Two pair beats one pair. Hand B wins.",
  },
  {
    flop: [["4","♠"],["4","♥"],["4","♦"]],
    turn: ["K","♣"], river: ["2","♥"],
    handA: [["A","♣"],["J","♦"]],
    handB: [["Q","♥"],["J","♥"]],
    explain: "The board flopped trip fours. Neither player has a four. Both play 4-4-4 plus their two best kickers. Hand A has A-K kickers (using the K from the board and their ace); Hand B has K-Q. Ace beats Queen in the kicker. Hand A wins.",
  },
  {
    flop: [["J","♠"],["9","♥"],["5","♣"]],
    turn: ["10","♦"], river: ["8","♣"],
    handA: [["Q","♥"],["K","♠"]],
    handB: [["7","♣"],["6","♦"]],
    explain: "Hand A makes a K-high straight (K-Q-J-10-9) using both their cards. Hand B makes a J-high straight (J-10-9-8-7) using only the 7 from hand. Higher straight wins. Hand A.",
  },
  {
    flop: [["J","♣"],["8","♣"],["4","♣"]],
    turn: ["K","♠"], river: ["2","♦"],
    handA: [["J","♠"],["J","♥"]],
    handB: [["A","♣"],["5","♣"]],
    explain: "Hand A flopped top set (jacks). Hand B flopped the nut flush — three clubs on the board plus two in hand makes an ace-high flush. Flush beats set. Sets on monotone boards are usually losers when someone has a flush card in hand.",
  },
  {
    flop: [["10","♦"],["7","♦"],["4","♦"]],
    turn: ["K","♦"], river: ["2","♠"],
    handA: [["A","♦"],["9","♣"]],
    handB: [["J","♦"],["5","♣"]],
    explain: "Four diamonds on the board. Hand A holds the Ace of diamonds — they make the nut flush (A-K-10-7-4). Hand B holds the Jack of diamonds — they make a king-high flush (K-J-10-7-4). Higher card in the flush wins. Hand A.",
  },
];

export const PREFLOP_QUIZ = [
  {
    pos: "UTG", cards: [["A","♠"],["A","♥"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Pocket aces are the strongest preflop hand. Always raise for value — never slow-play from early position. You want to build the pot and thin the field.",
  },
  {
    pos: "UTG", cards: [["K","♥"],["7","♣"]],
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "Offsuit K-7 is a trap from UTG. You're dominated by KQ, KJ, KT, AK, and you have eight players left to act. Easy fold.",
  },
  {
    pos: "BTN", cards: [["A","♣"],["5","♣"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Suited ace on the button — open it. You have position post-flop, the wheel-draw potential, nut-flush potential, and you can steal the blinds.",
  },
  {
    pos: "MP", cards: [["7","♥"],["2","♦"]],
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "Statistically the worst hand in Hold'em. No straight potential, offsuit, dominated by basically everything. Fold from any position.",
  },
  {
    spotType: "Facing Open",
    table: "6-max cash",
    stackBB: 100,
    pos: "BB", cards: [["Q","♠"],["Q","♦"]],
    prompt: "Button opens to 2.5bb. You are in the big blind with Q♠Q♦. Best action?",
    answer: "3-bet",
    options: ["Fold", "Call", "3-bet"],
    explain: "Pocket queens are a premium hand and a clear value 3-bet versus a button open. Calling can exist in some slow-play mixes, but the clean default is to re-raise for value and deny equity.",
  },
  {
    pos: "CO", cards: [["J","♠"],["10","♠"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Suited connectors from the cutoff are a clear open. Strong straight and flush potential, plus you have position on most opponents post-flop.",
  },
  {
    pos: "SB", cards: [["9","♣"],["3","♥"]],
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "From the SB you'll always be out of position post-flop. Junk hands like 9-3 offsuit lose money even getting in cheap. The half-blind isn't a discount worth taking.",
  },
  {
    pos: "UTG", cards: [["K","♠"],["K","♦"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Pocket kings — the second-strongest starting hand. Raise for value from anywhere. Don't get cute trying to trap; build the pot now.",
  },
  {
    pos: "HJ", cards: [["A","♥"],["Q","♥"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Suited A-Q is premium. Open-raise from the hijack to build a pot in position with a strong, high-equity hand that flops well.",
  },
  {
    pos: "MP", cards: [["8","♦"],["8","♣"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Pocket eights from middle position are an open-raise. Against tighter ranges from EP/MP, raise; against wider ranges (button), still raise. Set-mining hand with showdown value.",
  },
  {
    pos: "BTN", cards: [["6","♥"],["5","♥"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Suited connectors on the button are a steal-and-play hand. Position lets you c-bet bluff, hit disguised straights/flushes, and pick up blinds when folded around.",
  },
  {
    pos: "CO", cards: [["A","♦"],["10","♣"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "A-T offsuit from the cutoff is a comfortable open. Watch out for getting 3-bet from the button or blinds — A-T offsuit doesn't love facing big resistance.",
  },
  {
    pos: "UTG", cards: [["A","♠"],["J","♦"]],
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "A-J offsuit is a famously trappy hand from UTG in tougher games. It's dominated by A-K, A-Q, and pocket pairs JJ+. In a tight 9-handed game, fold it. (Looser games: open it.)",
  },
  {
    spotType: "Facing Open",
    table: "6-max cash",
    stackBB: 100,
    pos: "SB", cards: [["A","♥"],["A","♦"]],
    prompt: "Button opens to 2.5bb. You are in the small blind with A♥A♦. Best action?",
    answer: "3-bet",
    options: ["Fold", "Call", "3-bet"],
    explain: "Pocket aces are the strongest starting hand. From the small blind facing an open, 3-bet for value. You are out of position post-flop, so building the pot and reducing multiway risk matters.",
  },
  {
    spotType: "Facing Open",
    table: "6-max cash",
    stackBB: 100,
    pos: "BB", cards: [["10","♥"],["9","♣"]],
    prompt: "Button opens to 2.2bb. Small blind folds. You are in the big blind with T♥9♣. Best action?",
    answer: "Call",
    options: ["Fold", "Call", "3-bet"],
    explain: "T9 offsuit is a marginal but reasonable defend versus a small button open. You are getting good pot odds, close the action, and have some straight potential. Versus an early-position open or larger sizing, this becomes a fold much more often.",
  },
  {
    pos: "MP", cards: [["K","♥"],["J","♦"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "K-J offsuit from middle position is a standard open. Strong broadway, makes top pair often. Fold it from UTG in tight games; raise it from MP onwards.",
  },
  {
    spotType: "RFI",
    table: "6-max cash",
    stackBB: 100,
    pos: "UTG", cards: [["6","♣"],["6","♥"]],
    prompt: "Action folds to you UTG with 6♣6♥ at 100bb effective. Best default action?",
    answer: "Raise",
    options: ["Fold", "Raise"],
    explain: "Pocket sixes are a borderline but standard open in many 6-max cash ranges. In tighter full-ring games, folding can be reasonable. Open-limping/calling first-in is not the default strategy.",
  },
  {
    pos: "BTN", cards: [["Q","♦"],["10","♣"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Q-T offsuit from the button: open it. Folded around to you, you should raise about half of all hands. Q-T flops top pair, straights, and steals blinds when missed.",
  },
  {
    pos: "HJ", cards: [["7","♠"],["6","♠"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Suited connectors from the hijack: open. They flop well disguised — straights, flushes, and pair-plus-draw combos. Fold equity plus implied odds make these profitable.",
  },
  {
    pos: "CO", cards: [["3","♣"],["3","♦"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Pocket threes from the cutoff: raise. Against late-position calling ranges, you have set-mining equity and fold equity. Don't limp small pairs in late position.",
  },
  {
    spotType: "Facing Open",
    table: "6-max cash",
    stackBB: 100,
    pos: "SB", cards: [["A","♣"],["K","♣"]],
    prompt: "Cutoff opens to 2.5bb. Button folds. You are in the small blind with A♣K♣. Best action?",
    answer: "3-bet",
    options: ["Fold", "Call", "3-bet"],
    explain: "AK suited is a premium 3-bet from the small blind. Calling can exist in some advanced mixed strategies, but as a default, 3-bet for value and avoid playing a bloated multiway pot out of position.",
  },
  {
    pos: "BB", cards: [["J","♥"],["3","♦"]],
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "Even from the big blind facing a single open, J-3 offsuit is too weak to defend profitably. Defending too wide from the BB bleeds chips. Fold the trash.",
  },
  {
    spotType: "RFI",
    table: "6-max cash",
    stackBB: 100,
    pos: "UTG", cards: [["Q","♥"],["J","♥"]],
    prompt: "Action folds to you UTG with Q♥J♥ at 100bb effective. Best default action?",
    answer: "Raise",
    options: ["Fold", "Raise"],
    explain: "QJs is a borderline but playable UTG open in many 6-max cash ranges because it is suited, connected, and has broadway value. In tighter full-ring games, folding is reasonable. Calling first-in is not a strong default.",
  },
  {
    spotType: "RFI",
    table: "6-max cash",
    stackBB: 100,
    pos: "BTN", cards: [["2","♦"],["2","♥"]],
    prompt: "Action folds to you on the button with 2♦2♥ at 100bb effective. Best action?",
    answer: "Raise",
    options: ["Fold", "Raise"],
    explain: "Any pocket pair is usually opened from the button when folded to. You gain fold equity, have position post-flop, and can still flop sets. This is not the same as facing an early-position open.",
  },
  {
    pos: "CO", cards: [["K","♦"],["10","♥"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "K-T offsuit from the cutoff is a clear open. Strong broadway with showdown value. Fold to a 3-bet from the BB — they have all the AK and big pairs.",
  },
  {
    pos: "MP", cards: [["A","♠"],["7","♦"]],
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "A-7 offsuit from middle position is too weak. Dominated by every higher ace, and your kicker plays poorly when you flop top pair. Wait for better.",
  },
  {
    pos: "BTN", cards: [["8","♣"],["7","♣"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Suited connectors on the button — raise every time. High equity to flop straight draws, flush draws, two pair, sets, and combo draws. The button's bread-and-butter speculative hand.",
  },
  {
    pos: "UTG", cards: [["10","♠"],["10","♦"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Pocket tens from UTG: raise. Don't get fancy. You have a top-15 starting hand; play it straightforwardly. If you get 4-bet, you can usually fold, but for now: raise.",
  },
  {
    spotType: "Facing Open",
    table: "6-max cash",
    stackBB: 100,
    pos: "BB", cards: [["K","♥"],["Q","♦"]],
    prompt: "Button opens to 2.5bb. Small blind folds. You are in the big blind with K♥Q♦. Best aggressive default?",
    answer: "3-bet",
    options: ["Fold", "Call", "3-bet"],
    explain: "KQo is strong enough to continue versus a button open. Calling is standard in many ranges, but 3-betting is a good aggressive default against wide late-position opens because it gains initiative, denies equity, and gets value from worse broadways.",
  },
  {
    pos: "HJ", cards: [["9","♥"],["9","♦"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Pocket nines from the hijack: raise. Solid pair, set-mining equity, and you have position over MP and the blinds. Fold to a tight UTG 3-bet.",
  },
  {
    pos: "SB", cards: [["Q","♣"],["10","♥"]],
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "Q-T offsuit from the small blind facing an open: fold. You'll be out of position the rest of the hand, and Q-T offsuit is too weak to 3-bet for value. Don't get talked into 'half-pricing.'",
  },
  {
    pos: "CO", cards: [["5","♥"],["5","♦"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Pocket fives from the cutoff: raise. Set-mining hand with showdown value. Open small in tight games to keep your range balanced; standard size in normal games.",
  },
  {
    pos: "BTN", cards: [["A","♠"],["K","♣"]],
    prompt: "UTG opens to 2.5bb. Folds to you on the button with A-K offsuit at 100bb effective. Best action?",
    answer: "3-bet",
    options: ["Fold", "Call", "3-bet"],
    explain: "A-K offsuit is a high-frequency value 3-bet versus UTG. It dominates portions of continuing ranges and benefits from initiative.",
  },
  {
    pos: "BB", cards: [["K","♠"],["9","♠"]],
    prompt: "Cutoff opens min-raise to 2bb. You are in the big blind with K-9 suited, 100bb deep. Decision?",
    answer: "Call",
    options: ["Fold", "Call", "3-bet"],
    explain: "K9s defends well versus late opens because of pot odds and playability. Calling is standard; 3-bet mix is acceptable versus weak players.",
  },
  {
    pos: "SB", cards: [["A","♣"],["5","♣"]],
    prompt: "Button opens to 2.2bb. You are in the small blind with A-5 suited. Best default line?",
    answer: "3-bet",
    options: ["Fold", "Call", "3-bet"],
    explain: "A5s is a classic small-blind 3-bet candidate: blocker value, wheel potential, and it avoids weak out-of-position flats.",
  },
  {
    pos: "CO", cards: [["Q","♣"],["J","♦"]],
    prompt: "UTG opens to 3bb and action folds to you in cutoff with Q-J offsuit. What is best in most live pools?",
    answer: "Fold",
    options: ["Fold", "Call", "3-bet"],
    explain: "QJo performs poorly versus strong early-position ranges and creates dominated top-pair spots. Folding is disciplined and profitable long term.",
  },
  {
    pos: "BTN", cards: [["7","♠"],["6","♠"]],
    prompt: "Hijack opens 2.5bb. You're on the button with 7-6 suited and both blinds are straightforward. Action?",
    answer: "Call",
    options: ["Fold", "Call", "3-bet"],
    explain: "Button call is standard: suited connectors realize equity well in position and can win large pots when they connect hard.",
  },
  {
    pos: "HJ", cards: [["Q","♠"],["Q","♥"]],
    prompt: "You open HJ to 2.5bb with QQ. CO 3-bets to 8.5bb, others fold. Best baseline response at 100bb?",
    answer: "4-bet",
    options: ["Fold", "Call", "4-bet"],
    explain: "QQ is too strong to fold and usually wants to 4-bet for value/protection against aggressive cutoff 3-bet ranges.",
  },
  {
    pos: "BB", cards: [["A","♣"],["J","♣"]],
    prompt: "Button opens 2.2bb. You are in BB with A-J suited. Preferred action?",
    answer: "3-bet",
    options: ["Fold", "Call", "3-bet"],
    explain: "AJs is ahead of many button opens and benefits from denying equity. 3-betting captures value and simplifies many runouts.",
  },
  {
    pos: "UTG", cards: [["7","♣"],["7","♠"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Pocket sevens are a clear open from UTG in 6-max. Set-mine equity plus enough showdown value. Don't open-limp; raise.",
  },
  {
    pos: "UTG", cards: [["A","♥"],["Q","♠"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "A-Q offsuit is a standard UTG open. Premium broadway with strong equity vs flatting ranges. Be cautious facing a 4-bet.",
  },
  {
    pos: "UTG", cards: [["9","♠"],["8","♠"]],
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "98s is on the bubble from UTG. In tight 6-max games most solvers fold or open at very low frequency. Folding here keeps your UTG range strong and avoids tricky multiway spots.",
  },
  {
    pos: "MP", cards: [["J","♣"],["J","♦"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Pocket jacks from middle position: open-raise. Strong overpair to most flops. Reassess if you face a 3-bet from a tight player.",
  },
  {
    pos: "MP", cards: [["A","♦"],["K","♣"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "A-K offsuit is a top-five preflop hand. Raise from any position. If you're 3-bet, you usually 4-bet or call depending on stack depth.",
  },
  {
    pos: "MP", cards: [["6","♦"],["6","♣"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Pocket sixes from MP: raise. Set-mining hand with thin showdown value. Avoid the limp; opening builds initiative.",
  },
  {
    pos: "MP", cards: [["8","♥"],["7","♣"]],
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "8-7 offsuit from MP is a fold. No suit, no premium broadway, dominated by every higher connector. Wait for a better spot.",
  },
  {
    pos: "HJ", cards: [["A","♣"],["10","♣"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Suited ace-ten from the hijack is a comfortable open. Nut flush potential, broadway equity, good playability.",
  },
  {
    pos: "HJ", cards: [["K","♠"],["Q","♠"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Suited K-Q is a premium broadway. Always open. You can comfortably continue versus most 3-bets.",
  },
  {
    pos: "HJ", cards: [["4","♥"],["4","♦"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Pocket fours from the hijack: raise. Small pair, but you'll flop a set ~12% of the time and have fold equity preflop.",
  },
  {
    pos: "HJ", cards: [["Q","♣"],["8","♥"]],
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "Q-8 offsuit is too weak even from the hijack. Dominated by every Qx-better and every broadway. Fold.",
  },
  {
    pos: "CO", cards: [["A","♥"],["9","♣"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Ace-nine offsuit from the cutoff is a standard open. Equity advantage versus blinds, plus blocker value. Avoid getting all-in against tight resistance.",
  },
  {
    pos: "CO", cards: [["K","♦"],["J","♦"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Suited K-J is an automatic cutoff open. Strong equity, flush draws, and broadway top pairs.",
  },
  {
    pos: "CO", cards: [["9","♠"],["8","♠"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Suited connectors from the cutoff: raise. Excellent playability — straight draws, flush draws, and top-pair potential with position.",
  },
  {
    pos: "CO", cards: [["J","♥"],["8","♦"]],
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "J-8 offsuit from the cutoff is borderline at best, usually a fold in standard cash ranges. Disconnected, offsuit, dominated by every J-better.",
  },
  {
    pos: "BTN", cards: [["A","♣"],["3","♣"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Suited ace on the button is an open every time. Wheel and nut-flush potential, plus blind-steal equity. Default raise.",
  },
  {
    pos: "BTN", cards: [["K","♥"],["8","♥"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Suited K-8 on the button: open. Flop top pairs, flush draws, and grab blinds when folded around. The button's whole job is steal-and-play.",
  },
  {
    pos: "BTN", cards: [["J","♦"],["9","♠"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "J-9 offsuit on the button is in the open range when folded to. Position lets you outplay opponents post-flop with marginal holdings.",
  },
  {
    pos: "BTN", cards: [["5","♠"],["4","♠"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Small suited connectors on the button: raise. Big implied odds, disguised value when you flop two pair or a straight.",
  },
  {
    pos: "BTN", cards: [["9","♥"],["7","♣"]],
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "9-7 offsuit on the button is on the edge. In most modern solver ranges this is a fold — gapped, offsuit, and dominated when you flop top pair. Skip it.",
  },
  {
    spotType: "RFI",
    table: "6-max cash",
    stackBB: 100,
    pos: "SB", cards: [["8","♣"],["8","♠"]],
    prompt: "Action folds to you in the small blind with 8♣8♠ at 100bb effective. Best default action?",
    answer: "Raise",
    options: ["Fold", "Raise"],
    explain: "Pocket eights from the SB when folded to: raise. Limping in is a leak — you get no fold equity and play out of position with no initiative. Open to take it down or play heads-up versus the BB.",
  },
  {
    spotType: "RFI",
    table: "6-max cash",
    stackBB: 100,
    pos: "SB", cards: [["A","♦"],["10","♥"]],
    prompt: "Action folds to you in the small blind with A♦T♥ at 100bb effective. Best default action?",
    answer: "Raise",
    options: ["Fold", "Raise"],
    explain: "A-T offsuit is well above the SB open threshold when folded to. Raise — even offsuit aces have enough equity vs the BB's defending range.",
  },
  {
    spotType: "Facing Open",
    table: "6-max cash",
    stackBB: 100,
    pos: "SB", cards: [["K","♣"],["K","♥"]],
    prompt: "Cutoff opens to 2.5bb. Button folds. You are in the small blind with K♣K♥. Best action?",
    answer: "3-bet",
    options: ["Fold", "Call", "3-bet"],
    explain: "Pocket kings from the SB facing a CO open: 3-bet for value. You don't want to flat with the second-best preflop hand out of position and let the BB squeeze.",
  },
  {
    spotType: "Facing Open",
    table: "6-max cash",
    stackBB: 100,
    pos: "BB", cards: [["J","♥"],["J","♣"]],
    prompt: "Button opens to 2.5bb. Small blind folds. You are in the big blind with J♥J♣. Best action?",
    answer: "3-bet",
    options: ["Fold", "Call", "3-bet"],
    explain: "Jacks from the BB facing a wide button open: 3-bet. You dominate worse pairs and broadways and want to play a bigger pot heads-up with initiative.",
  },
  {
    spotType: "Facing Open",
    table: "6-max cash",
    stackBB: 100,
    pos: "BB", cards: [["A","♦"],["K","♣"]],
    prompt: "UTG opens to 2.5bb. Folds to you in the big blind with A♦K♣. Best action?",
    answer: "3-bet",
    options: ["Fold", "Call", "3-bet"],
    explain: "A-K offsuit facing a UTG open: 3-bet. You're ahead of most of their range and gain initiative. A flat is acceptable in some ranges but the clean default is to raise.",
  },
  {
    spotType: "Facing Open",
    table: "6-max cash",
    stackBB: 100,
    pos: "BB", cards: [["10","♥"],["10","♦"]],
    prompt: "Cutoff opens to 2.5bb. Folds to you in the big blind with T♥T♦. Best action?",
    answer: "3-bet",
    options: ["Fold", "Call", "3-bet"],
    explain: "Pocket tens versus a cutoff open is a clear 3-bet. You're ahead of every smaller pocket pair and most broadways. Playing a 3-bet pot heads-up beats a multiway flat.",
  },
  {
    spotType: "Facing Open",
    table: "6-max cash",
    stackBB: 100,
    pos: "BB", cards: [["7","♥"],["6","♥"]],
    prompt: "UTG opens to 2.5bb. Folds to you in the big blind with 7♥6♥. Best action?",
    answer: "Call",
    options: ["Fold", "Call", "3-bet"],
    explain: "76 suited is a clean defend from the BB versus a UTG open. Closing the action with great pot odds and a connected, suited hand. 3-betting bleeds money out of position; folding is too tight.",
  },
  {
    spotType: "Facing Open",
    table: "6-max cash",
    stackBB: 100,
    pos: "BB", cards: [["Q","♥"],["J","♦"]],
    prompt: "Button opens to 2.2bb. Small blind folds. You are in the big blind with Q♥J♦. Best action?",
    answer: "Call",
    options: ["Fold", "Call", "3-bet"],
    explain: "QJ offsuit defends comfortably against a small button open. Has equity vs the wide button range. 3-betting is a mixed action but flatting is the clean default.",
  },
  {
    spotType: "Facing Open",
    table: "6-max cash",
    stackBB: 100,
    pos: "BB", cards: [["5","♠"],["5","♣"]],
    prompt: "Button opens to 2.5bb. Small blind folds. You are in the big blind with 5♠5♣. Best action?",
    answer: "Call",
    options: ["Fold", "Call", "3-bet"],
    explain: "Small pocket pairs prefer to flat from the BB and try to flop a set. 3-betting bloats the pot when you'll miss often; folding gives up easy equity.",
  },
  {
    spotType: "Facing Open",
    table: "6-max cash",
    stackBB: 100,
    pos: "BB", cards: [["10","♠"],["5","♦"]],
    prompt: "UTG opens to 3bb. Folds to you in the big blind with T♠5♦. Best action?",
    answer: "Fold",
    options: ["Fold", "Call", "3-bet"],
    explain: "T-5 offsuit versus a UTG raise is too weak to continue. Even from the BB, defending too wide vs tight ranges and big sizings just hemorrhages chips. Easy fold.",
  },
];

export const POSTFLOP_QUIZ = [
  {
    hole: [["A","♠"],["K","♠"]], board: [["Q","♠"],["7","♠"],["3","♥"]],
    pot: 60, toCall: 30,
    prompt: "You hold A-K of spades. Flop comes Q-7♠-3♥. Opponent bets half-pot. What's your move?",
    answer: "Call/Raise",
    options: ["Fold", "Call/Raise", "Min-raise only"],
    explain: "You have the nut flush draw plus two overcards, although the overcard outs are not always clean. Versus a half-pot bet, this is a clear continue. Calling is standard; raising can be used as a semi-bluff because it adds fold equity.",
  },
  {
    hole: [["10","♥"],["10","♦"]], board: [["A","♣"],["K","♠"],["7","♥"]],
    pot: 80, toCall: 60,
    prompt: "You have pocket tens. Flop is A-K-7 rainbow. Aggressive opponent leads big into you. Decision?",
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "Two overcards on the flop is the worst-case scenario for an underpair. You're getting 2.3-to-1 but realistically have 2 outs (8% to hit a set). Against a player betting big into a coordinated board, fold and save your stack.",
  },
  {
    hole: [["J","♣"],["10","♣"]], board: [["9","♣"],["8","♣"],["2","♥"]],
    pot: 50, toCall: 0,
    prompt: "You have J-10 of clubs. Flop is 9♣-8♣-2♥. You're first to act. What's the play?",
    answer: "Bet",
    options: ["Check", "Bet", "Check-fold"],
    explain: "This is a monster combo draw: open-ended straight draw, flush draw, straight-flush potential, and some overcard value. You have around 15 primary draw outs before considering overcards. Betting as a semi-bluff is strong because you can win immediately or build a pot when you improve.",
  },
  {
    hole: [["A","♥"],["A","♦"]], board: [["9","♣"],["8","♣"],["7","♣"]],
    pot: 100, toCall: 80,
    prompt: "Pocket aces. Flop is 9-8-7 all clubs. Opponent shoves. Your aces are red. What now?",
    answer: "Fold",
    options: ["Fold", "Call", "Snap-call"],
    explain: "A wet board and a shove put your red aces in a bad spot. You lose to made flushes, straights, sets, two pair, and huge combo draws, and you have no club redraw. Unless villain is wildly over-bluffing, folding is the disciplined default.",
  },
  {
    hole: [["K","♠"],["Q","♥"]], board: [["K","♦"],["7","♣"],["2","♠"]],
    pot: 40, toCall: 0,
    prompt: "K-Q offsuit. Flop K-7-2 rainbow. You raised preflop and got one caller. They check to you. What's your action?",
    answer: "Bet",
    options: ["Check", "Bet", "Check-raise plan"],
    explain: "Top pair, strong kicker, dry board. You should c-bet for value and protection. Check gives free cards to underpairs and overcards on later streets. Bet around 1/2 to 2/3 pot.",
  },
  {
    hole: [["7","♦"],["7","♥"]], board: [["7","♠"],["K","♣"],["2","♥"]],
    pot: 30, toCall: 0,
    prompt: "Pocket sevens. Flop comes 7-K-2 rainbow. You raised preflop, got two callers, and you're first to act. Action?",
    answer: "Bet",
    options: ["Check", "Bet", "Slow-play"],
    explain: "Bottom set on a dry board with two opponents — bet for value. Slow-playing leaks value here; nothing scary is coming, and someone has a king they'll pay you off with. Build the pot now.",
  },
  {
    hole: [["A","♣"],["Q","♣"]], board: [["J","♥"],["8","♦"],["3","♣"]],
    pot: 24, toCall: 0,
    prompt: "A-Q suited. Flop J-8-3 rainbow. You raised preflop, BB called. They check. What's the standard play?",
    answer: "Bet",
    options: ["Check", "Bet", "Big bet"],
    explain: "Standard c-bet spot. Even though you missed, the board hits your range better than the BB's calling range. Bet around 1/3 pot — get folds from underpairs and air, give up cheap if check-raised.",
  },
  {
    hole: [["Q","♥"],["Q","♦"]], board: [["A","♠"],["10","♥"],["6","♦"]],
    pot: 60, toCall: 40,
    prompt: "Pocket queens. Flop A-10-6 rainbow. Tight opponent leads 2/3 pot into you. Decision?",
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "An ace-high flop and a tight opponent leading into a multi-way pot is a classic 'one-pair trap.' QQ is now a bluff catcher with 2 outs to a set. Against tight bettors who don't bluff enough, fold.",
  },
  {
    hole: [["6","♥"],["5","♥"]], board: [["7","♥"],["8","♥"],["K","♣"]],
    pot: 40, toCall: 30,
    prompt: "6-5 of hearts. Flop 7♥-8♥-K♣. Opponent bets 3/4 pot. What's the play?",
    answer: "Call",
    options: ["Fold", "Call", "Raise"],
    explain: "You have a flush draw (9 outs) AND an open-ended straight draw (8 outs, but 2 overlap with flush) = 15 clean outs. About 54% equity to make a hand by the river. Easy call. Raising also fine, but call works.",
  },
  {
    hole: [["A","♦"],["8","♦"]], board: [["K","♦"],["7","♦"],["4","♦"]],
    pot: 50, toCall: 35,
    prompt: "A-8 of diamonds. Flop is K-7-4 all diamonds. Opponent leads big. Decision?",
    answer: "Call",
    options: ["Fold", "Call", "Raise"],
    explain: "You have the nut flush already. Calling is a strong trap line, especially in position, because it keeps bluffs and worse value hands in. Raising is also viable against players who will continue with worse flushes, sets, or strong Kx with a diamond.",
  },
  {
    hole: [["10","♠"],["9","♠"]], board: [["J","♦"],["8","♣"],["2","♥"]],
    pot: 30, toCall: 20,
    prompt: "10-9 suited. Flop is J-8-2 rainbow. Opponent bets 2/3 pot. What's the play?",
    answer: "Call",
    options: ["Fold", "Call", "Raise"],
    explain: "Open-ended straight draw — 8 outs, about 32% by river. Pot odds give you ~28% needed. With implied odds (you'll get paid when you hit), this is a clear call. Don't raise; you have a draw, not a made hand.",
  },
  {
    hole: [["A","♥"],["K","♣"]], board: [["2","♠"],["7","♦"],["10","♣"]],
    pot: 40, toCall: 0,
    prompt: "A-K offsuit, you raised preflop. Flop comes 2-7-10 rainbow. BB checks to you. Standard play?",
    answer: "Bet",
    options: ["Check", "Bet", "Check-raise plan"],
    explain: "Standard small c-bet. The board misses BB's calling range often. Bet 1/3 pot to fold out underpairs and air, while leaving yourself easy give-up if check-raised. AK has 6 outs to overcards even if called.",
  },
  {
    hole: [["8","♠"],["8","♣"]], board: [["A","♦"],["A","♣"],["6","♥"]],
    pot: 30, toCall: 22,
    prompt: "Pocket eights. Flop comes A-A-6. Opponent leads 2/3 pot. Decision?",
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "Paired ace board is the worst for underpairs. They have an ace, a bigger pocket pair, or are bluffing — but folding ranges hit one of those two more often than the bluff. Fold and move on.",
  },
  {
    hole: [["K","♦"],["Q","♦"]], board: [["10","♦"],["9","♦"],["3","♣"]],
    pot: 24, toCall: 0,
    prompt: "K-Q of diamonds. Flop is 10♦-9♦-3♣. You're in position vs one caller. They check. Action?",
    answer: "Bet",
    options: ["Check", "Bet", "Check-raise plan"],
    explain: "Massive equity hand — flush draw + gutshot + two overcards. 14+ outs, about 55% equity. Bet for the semi-bluff: you fold out weak hands, build the pot for when you hit, and gain initiative.",
  },
  {
    hole: [["9","♦"],["9","♣"]], board: [["Q","♥"],["J","♠"],["10","♦"]],
    pot: 40, toCall: 30,
    prompt: "Pocket nines. Flop is Q-J-10 rainbow. Opponent bets 3/4 pot. What's the play?",
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "Three Broadway cards on the flop is brutal for an underpair. Anyone with K, 9, or any pocket pair JJ+ is ahead. Plus there's only one card to give you a straight (anything but K is bad). Fold.",
  },
  {
    hole: [["A","♠"],["A","♣"]], board: [["K","♥"],["7","♦"],["2","♠"]],
    pot: 20, toCall: 0,
    prompt: "Pocket aces, you 3-bet preflop. Flop is K-7-2 rainbow. Opponent checks to you. Standard play?",
    answer: "Bet",
    options: ["Check", "Bet", "Check to trap"],
    explain: "Continuation bet for value. Don't slow-play AA on dry boards — your opponent can't catch up easily, and they may have AK paying you off. C-bet around 2/3 pot.",
  },
  {
    hole: [["J","♥"],["J","♦"]], board: [["A","♥"],["A","♣"],["J","♠"]],
    pot: 50, toCall: 35,
    prompt: "Pocket jacks. Flop is A-A-J. Opponent shoves all-in. Decision?",
    answer: "Call",
    options: ["Fold", "Call", "Tank-fold"],
    explain: "Jacks full of aces. The only hands beating you are quad aces (3 combos) and AJ for aces full of jacks (2 combos). Five combos beat you, dozens don't. Snap-call.",
  },
  {
    hole: [["7","♣"],["6","♣"]], board: [["8","♣"],["5","♥"],["2","♦"]],
    pot: 30, toCall: 0,
    prompt: "7-6 of clubs. Flop is 8♣-5-2 rainbow. You called from BB; SB checks to you. Action?",
    answer: "Bet",
    options: ["Check", "Bet", "Massive bet"],
    explain: "Open-ended straight draw + backdoor flush draw. Bet for semi-bluff value. You either fold them out, or build the pot for your draw. Check is fine too, but betting puts maximum pressure on weak made hands.",
  },
  {
    hole: [["K","♣"],["K","♦"]], board: [["A","♠"],["8","♥"],["3","♣"]],
    pot: 40, toCall: 30,
    prompt: "Pocket kings. Flop A-8-3 rainbow. Opponent leads 3/4 pot. What's the play?",
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "When pocket kings see an ace on the flop and an opponent leads big, the math is grim. Most leaders here have an ace. KK is now a 2-out hand. Fold and don't fall in love with your overpair.",
  },
  {
    hole: [["Q","♠"],["J","♠"]], board: [["10","♠"],["9","♠"],["2","♥"]],
    pot: 24, toCall: 0,
    prompt: "Q-J of spades. Flop 10♠-9♠-2♥. Heads-up, opponent checks to you. Action?",
    answer: "Bet",
    options: ["Check", "Bet", "Min-bet"],
    explain: "Flush draw plus open-ended straight draw plus overcards makes this one of the strongest semi-bluff candidates. Not every overcard out is clean, but your equity and fold equity are excellent. Betting is the best default.",

  },
  {
    hole: [["A","♣"],["J","♣"]], board: [["J","♦"],["7","♠"],["2","♣"]],
    pot: 36, toCall: 18,
    prompt: "You open MP with A-J suited. BB check-calls flop J-7-2 rainbow, then leads half-pot on the turn 9♥. Best default?",
    answer: "Call",
    options: ["Fold", "Call", "Raise"],
    explain: "Top pair top kicker should continue against a half-pot donk on a relatively dry texture. Raising isolates against stronger hands; calling keeps dominated Jx and bluffs in.",
  },
  {
    hole: [["K","♠"],["Q","♠"]], board: [["A","♠"],["10","♦"],["4","♠"]],
    pot: 50, toCall: 20,
    prompt: "Flop A♠-10♦-4♠. Opponent c-bets 40% pot. You hold K-Q♠. Best action?",
    answer: "Call",
    options: ["Fold", "Call", "Raise"],
    explain: "Nut-adjacent flush draw plus two overcards yields strong equity and positional flexibility. Calling realizes equity cleanly without inflating variance.",
  },
  {
    hole: [["Q","♦"],["Q","♣"]], board: [["8","♥"],["8","♣"],["4","♠"]],
    pot: 42, toCall: 0,
    prompt: "You 3-bet preflop with QQ and see 8-8-4 rainbow. Villain checks. What is best?",
    answer: "Bet",
    options: ["Check", "Bet", "Overbet"],
    explain: "Paired dry boards favor the aggressor's overpairs. Small to medium c-bet gets value from pocket pairs and denies two overcards.",
  },
  {
    hole: [["A","♥"],["5","♥"]], board: [["K","♥"],["J","♥"],["8","♣"]],
    pot: 48, toCall: 36,
    prompt: "You face a 75% pot bet on K♥-J♥-8♣ with A♥5♥. Decision?",
    answer: "Call",
    options: ["Fold", "Call", "Raise"],
    explain: "Nut flush draw with overcard blocker and backdoor wheel routes has ample equity to continue. Raising can be mixed; call is stable default.",
  },
  {
    hole: [["9","♠"],["9","♥"]], board: [["A","♣"],["9","♦"],["6","♣"]],
    pot: 55, toCall: 0,
    prompt: "Single-raised pot. You flop middle set on A-9-6 two clubs and villain checks. Preferred line?",
    answer: "Bet",
    options: ["Check", "Bet", "Check-back always"],
    explain: "On draw-heavy ace-high boards, set wants value immediately from top pairs and draws. Slow-play allows many bad turn cards.",
  },
  {
    hole: [["K","♣"],["J","♣"]], board: [["Q","♠"],["10","♦"],["3","♥"]],
    pot: 32, toCall: 16,
    prompt: "You hold KJ with open-ended straight draw on Q-10-3 rainbow. Facing half-pot c-bet. Best action?",
    answer: "Call",
    options: ["Fold", "Call", "Raise all-in"],
    explain: "Open-ender has solid direct equity and implied odds. Calling is standard; ripping all-in is unnecessary overplay at deep stacks.",
  },
  {
    hole: [["A","♦"],["Q","♠"]], board: [["Q","♥"],["8","♦"],["5","♠"]],
    pot: 38, toCall: 0,
    prompt: "You c-bet flop with top pair top kicker and get called. Turn is 2♣, villain checks again. Continue?",
    answer: "Bet",
    options: ["Check", "Bet", "Give up"],
    explain: "Blank turn after call still allows value from Qx worse kickers, 8x, and stubborn pairs. A controlled second barrel is standard.",
  },
  {
    hole: [["7","♠"],["7","♣"]], board: [["K","♦"],["Q","♦"],["4","♥"]],
    pot: 44, toCall: 30,
    prompt: "You face a 68% pot c-bet on K-Q-4 with pocket sevens and no diamond. Action?",
    answer: "Fold",
    options: ["Fold", "Call", "Raise bluff"],
    explain: "Underpair with poor backdoors and two overcards is a classic over-defend trap. Without relevant blockers or draws, fold cleanly.",
  },
  {
    hole: [["A","♠"],["A","♦"]], board: [["7","♥"],["3","♣"]],
    pot: 30, toCall: 0,
    prompt: "You 3-bet preflop with pocket aces. Flop 7♥-3♣ rainbow goes check-check. Turn is 2♦. Villain checks again. Action?",
    answer: "Bet",
    options: ["Check", "Bet", "Big overbet"],
    explain: "Aces on a dry low board want value from any pair or float. A standard turn bet of half pot extracts from 7x, 33, and stubborn floats. Slow-playing AA here gives free cards for no reason.",
  },
  {
    hole: [["A","♣"],["K","♦"]], board: [["A","♠"],["10","♥"],["7","♣"]],
    pot: 30, toCall: 0,
    prompt: "You raise preflop with A-K and get one caller. Flop A-T-7 rainbow. Opponent checks. Action?",
    answer: "Bet",
    options: ["Check", "Bet", "Check to trap"],
    explain: "Top pair top kicker on a dry ace-high board is a clear c-bet for value. Don't slow-play — get value from worse aces and gut-shots. Bet around half pot.",
  },
  {
    hole: [["A","♥"],["A","♣"]], board: [["Q","♠"],["J","♠"],["10","♠"]],
    pot: 60, toCall: 50,
    prompt: "Pocket aces. Flop comes Q-J-10 all spades. Opponent leads big. Your aces are red. Decision?",
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "Worst possible flop for red aces. Straights, flushes, sets, two pair all in villain's range, with zero spade redraw. Your aces are now a bluff catcher with very few outs. Fold.",
  },
  {
    hole: [["J","♠"],["10","♠"]], board: [["9","♠"],["8","♠"],["3","♥"]],
    pot: 40, toCall: 30,
    prompt: "J-T of spades. Flop 9♠-8♠-3♥. Opponent leads 3/4 pot. Decision?",
    answer: "Call",
    options: ["Fold", "Call", "Raise"],
    explain: "Open-ended straight flush draw plus two overcards — about 21 outs, near 70% equity to make a hand by the river. Call (or raise) is mandatory. Calling keeps weaker hands in.",
  },
  {
    hole: [["K","♣"],["K","♥"]], board: [["8","♠"],["5","♦"],["2","♣"]],
    pot: 24, toCall: 0,
    prompt: "Pocket kings, you 3-bet preflop. Flop 8-5-2 rainbow. Opponent checks. Best action?",
    answer: "Bet",
    options: ["Check", "Bet", "Overbet"],
    explain: "Dry low flop, no overcards, your range crushes. C-bet small (around a third pot) for value and protection. Don't get fancy.",
  },
  {
    hole: [["A","♦"],["Q","♦"]], board: [["K","♣"],["J","♥"],["7","♠"]],
    pot: 36, toCall: 24,
    prompt: "A-Q of diamonds. Flop K-J-7 rainbow. Opponent leads 2/3 pot. What's the play?",
    answer: "Call",
    options: ["Fold", "Call", "Raise"],
    explain: "Gutshot to broadway plus two overcards (one of which is the nut blocker). Roughly 10 clean outs and good implied odds when you hit the ten. Easy call, not strong enough to raise.",
  },
  {
    hole: [["9","♠"],["9","♦"]], board: [["K","♣"],["6","♥"],["2","♠"]],
    pot: 28, toCall: 18,
    prompt: "Pocket nines. Flop K-6-2 rainbow. Opponent leads small (about 1/3 pot). Decision?",
    answer: "Call",
    options: ["Fold", "Call", "Raise"],
    explain: "Against a small lead, calling is correct. You have a pocket pair, the board is dry, and the price is great. Folding to small bets with an underpair on dry boards is a leak.",
  },
  {
    hole: [["10","♦"],["10","♣"]], board: [["8","♠"],["6","♥"],["2","♦"]],
    pot: 20, toCall: 0,
    prompt: "Pocket tens, you raised preflop and got one BB caller. Flop 8-6-2 rainbow. BB checks. Action?",
    answer: "Bet",
    options: ["Check", "Bet", "Check to trap"],
    explain: "Overpair on a dry, disconnected board. C-bet small for value and protection. Underpairs and weak gut-shots will fold or call worse.",
  },
  {
    hole: [["A","♣"],["A","♥"]], board: [["K","♠"],["10","♦"],["9","♣"],["2","♥"]],
    pot: 50, toCall: 40,
    prompt: "Pocket aces. Board K-T-9-2 rainbow. Opponent leads 80% pot on the turn after calling the flop. Decision?",
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "A flop-call/turn-lead from a non-spewy opponent on this texture screams two pair, set, or made straight. AA is now a thin bluff catcher with two outs to a set. Discipline matters. Fold.",
  },
  {
    hole: [["8","♥"],["8","♣"]], board: [["K","♦"],["Q","♣"],["8","♠"]],
    pot: 35, toCall: 0,
    prompt: "Pocket eights. Flop K-Q-8 rainbow. You're heads-up, opponent checks. Action?",
    answer: "Bet",
    options: ["Check", "Bet", "Check-raise plan"],
    explain: "Bottom set on a coordinated board needs to start building the pot. Bet for value and protection — too many turn cards bring straights and overcards that kill action.",
  },
  {
    hole: [["A","♠"],["10","♠"]], board: [["10","♥"],["10","♦"],["6","♣"]],
    pot: 22, toCall: 0,
    prompt: "A-T of spades. Flop is 10♥-10♦-6♣ — you flopped trips with the top kicker. Opponent checks. Action?",
    answer: "Bet",
    options: ["Check", "Bet", "Check to trap"],
    explain: "Trip tens with the ace kicker is a value-bet hand. Check is fine in small ranges but the standard play is to fire small — get value from underpairs and any 6, and from random floats.",
  },
  {
    hole: [["Q","♣"],["Q","♦"]], board: [["J","♥"],["6","♠"],["3","♣"]],
    pot: 30, toCall: 0,
    prompt: "Pocket queens, you 3-bet preflop. Flop is J-6-3 rainbow. Opponent checks. Action?",
    answer: "Bet",
    options: ["Check", "Bet", "Overbet"],
    explain: "Overpair on a low, dry board against a 3-bet caller's range. Bet — you have an equity advantage and want value from JX and underpairs.",
  },
  {
    hole: [["6","♠"],["6","♣"]], board: [["A","♣"],["K","♦"],["7","♥"]],
    pot: 22, toCall: 14,
    prompt: "Pocket sixes facing a 2/3-pot c-bet on A-K-7 rainbow from a solid regular. Decision?",
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "Two overcards, no draws, no backdoors that matter. Solid regs c-bet this board with a value-heavy range. Fold and save the chips.",
  },
  {
    hole: [["A","♥"],["K","♥"]], board: [["Q","♥"],["J","♥"],["2","♣"]],
    pot: 32, toCall: 0,
    prompt: "A-K of hearts. Flop Q♥-J♥-2♣. You're heads-up in position, opponent checks. Action?",
    answer: "Bet",
    options: ["Check", "Bet", "Trickier check"],
    explain: "Nut flush draw + gutshot to broadway + two overcards = over 60% equity. Bet for the semi-bluff. You either take it down, get called by worse, or build the pot for when you spike.",
  },
  {
    hole: [["A","♦"],["10","♦"]], board: [["10","♣"],["6","♥"],["6","♣"]],
    pot: 28, toCall: 0,
    prompt: "A-T of diamonds. Flop is T-6-6 with two clubs. Opponent checks. Action?",
    answer: "Bet",
    options: ["Check", "Bet", "Check to control pot"],
    explain: "Top pair top kicker on a paired board. Bet for value — sixes are unlikely in villain's range, while Tx and underpairs will pay you off. Check-back gives free cards on draw-heavy texture.",
  },
  {
    hole: [["J","♣"],["10","♣"]], board: [["9","♣"],["3","♦"],["2","♥"]],
    pot: 24, toCall: 16,
    prompt: "J-T of clubs. Flop 9♣-3♦-2♥. Opponent leads 2/3 pot. Action?",
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "Two overcards plus a backdoor flush is too thin to continue at 2/3 pot. Without a real draw, you'll miss the turn often and face another bet. Fold and find a better spot.",
  },
  {
    hole: [["A","♠"],["A","♥"]], board: [["7","♣"],["7","♦"],["3","♠"]],
    pot: 40, toCall: 0,
    prompt: "Pocket aces. Flop 7-7-3 rainbow. You're first to act heads-up. Action?",
    answer: "Bet",
    options: ["Check", "Bet", "Check-raise plan"],
    explain: "Overpair on a paired low board — your range is way ahead. Bet small for value. Don't slow-play; villain has plenty of pocket pairs and floats willing to call one bet.",
  },
  {
    hole: [["K","♥"],["K","♠"]], board: [["A","♥"],["A","♦"],["8","♠"]],
    pot: 25, toCall: 18,
    prompt: "Pocket kings. Flop A-A-8. Opponent leads 2/3 pot. Decision?",
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "Paired ace flop is brutal for KK. Villain's leading range contains aces, full houses, and overpair traps — and your two outs to make a boat are tiny. Folding loses the minimum.",
  },
  {
    hole: [["5","♣"],["5","♥"]], board: [["5","♠"],["8","♣"],["10","♥"]],
    pot: 30, toCall: 0,
    prompt: "Pocket fives. Flop is 5♠-8♣-T♥. Heads-up and opponent checks. Action?",
    answer: "Bet",
    options: ["Check", "Bet", "Check to trap"],
    explain: "Bottom set on a connected board. Bet — too many bad turn cards (any 6, 7, 9, J, Q, K) can scare action. Build the pot now while villain still has overpairs and broadways.",
  },
  {
    hole: [["A","♣"],["J","♥"]], board: [["A","♠"],["J","♦"],["8","♠"]],
    pot: 30, toCall: 0,
    prompt: "A-J offsuit. Flop is A♠-J♦-8♠. You raised preflop, BB called, BB checks. Action?",
    answer: "Bet",
    options: ["Check", "Bet", "Overbet"],
    explain: "Top two pair on a draw-heavy board. Bet for value and protection. The flush draw, gutshots, and Ax all have to pay something. Don't check and let a spade or 9 scare action.",
  },
  {
    hole: [["A","♦"],["K","♦"]], board: [["Q","♦"],["J","♦"],["7","♠"]],
    pot: 32, toCall: 22,
    prompt: "A-K of diamonds. Flop Q♦-J♦-7♠. Opponent leads 2/3 pot. Decision?",
    answer: "Call",
    options: ["Fold", "Call", "Raise"],
    explain: "Nut flush draw + gutshot to Broadway + two overcards. Around 18 clean outs, near 70% to improve. Calling realizes equity without bloating versus made hands; raising is acceptable as a semi-bluff.",
  },
  {
    hole: [["K","♠"],["K","♦"]], board: [["8","♥"],["7","♥"],["6","♣"]],
    pot: 28, toCall: 20,
    prompt: "Pocket kings. Flop 8♥-7♥-6♣. Opponent leads 2/3 pot. Decision?",
    answer: "Call",
    options: ["Fold", "Call", "Raise"],
    explain: "Wet board, but KK is still an overpair with plenty of equity vs villain's range of draws and weaker made hands. Calling controls pot size; raising bloats versus the actual straights and sets. Re-evaluate on the turn.",
  },
  {
    hole: [["J","♥"],["10","♦"]], board: [["J","♠"],["8","♣"],["3","♥"]],
    pot: 26, toCall: 18,
    prompt: "J-T offsuit. Flop J♠-8♣-3♥. Opponent leads 2/3 pot. Decision?",
    answer: "Call",
    options: ["Fold", "Call", "Raise"],
    explain: "Top pair with a decent kicker on a dry board. Call to keep bluffs in and worse Jx paying off. Raising isolates against stronger hands like overpairs and AJ.",
  },
  {
    hole: [["Q","♥"],["Q","♣"]], board: [["10","♥"],["6","♣"],["3","♠"]],
    pot: 36, toCall: 0,
    prompt: "Pocket queens, you 3-bet preflop. Flop T-6-3 rainbow. Opponent checks. Action?",
    answer: "Bet",
    options: ["Check", "Bet", "Overbet"],
    explain: "Overpair on a dry, disconnected board with range advantage. C-bet for value from TX and underpairs, and protection against random overcards.",
  },
  {
    hole: [["A","♠"],["Q","♥"]], board: [["K","♦"],["10","♣"],["4","♠"]],
    pot: 22, toCall: 0,
    prompt: "A-Q offsuit. Flop K-T-4 rainbow, you raised preflop and BB checks. Action?",
    answer: "Bet",
    options: ["Check", "Bet", "Give up"],
    explain: "Gutshot to Broadway plus two overcards (with the nut blocker). Bet — you have decent equity and your range smashes this flop. Folds out weak hands and gives you a strong barrel card on any A, Q, or J.",
  },
  {
    hole: [["8","♦"],["8","♣"]], board: [["7","♠"],["6","♦"],["5","♥"]],
    pot: 30, toCall: 22,
    prompt: "Pocket eights. Flop 7-6-5 rainbow. Opponent leads 3/4 pot. Decision?",
    answer: "Call",
    options: ["Fold", "Call", "Raise"],
    explain: "Overpair plus open-ended straight draw (a 4 or 9 makes a straight). Calling has good direct and implied odds; folding gives up too much equity. Raising bloats versus the made straights in villain's range.",
  },
  {
    hole: [["A","♣"],["K","♣"]], board: [["7","♣"],["4","♣"],["2","♦"]],
    pot: 24, toCall: 0,
    prompt: "A-K of clubs. Flop 7♣-4♣-2♦. You raised preflop, BB called, BB checks. Action?",
    answer: "Bet",
    options: ["Check", "Bet", "Min-bet"],
    explain: "Nut flush draw plus two overcards on a dry low board. Bet — you have huge equity, fold equity, and a card that lets you barrel turn (any club, A, or K).",
  },
  {
    hole: [["10","♥"],["10","♠"]], board: [["J","♣"],["J","♦"],["4","♥"]],
    pot: 28, toCall: 22,
    prompt: "Pocket tens. Flop J-J-4. Opponent leads 3/4 pot from out of position. Decision?",
    answer: "Call",
    options: ["Fold", "Call", "Raise"],
    explain: "Paired board with an underpair is a classic bluff-catch spot. Fold equity is gone, but so is much of villain's value range — pocket pairs lower than tens make up many combos. Call, then reassess on the turn.",
  },
  {
    hole: [["6","♥"],["6","♦"]], board: [["6","♣"],["A","♠"],["3","♥"]],
    pot: 30, toCall: 0,
    prompt: "Pocket sixes. Flop 6♣-A♠-3♥. You called preflop from the BB, raiser is heads-up. They check on the flop. Action?",
    answer: "Bet",
    options: ["Check", "Bet", "Slow-play"],
    explain: "Bottom set on an ace-high board with the preflop raiser giving up. A small donk extracts value from AX and gives a chance to barrel further. Slow-playing on this texture lets too many free cards reach the turn.",
  },
];

