// Poker quiz/scenario data
// Revised baseline:
// - Standard no-limit Texas Hold'em cash-game strategy.
// - Assume 100bb effective stacks unless a scenario says otherwise.
// - Assume no antes and no tournament ICM pressure.
// - Preflop "Call" is only used when hero is facing prior action.
// - If hero is first in, default options should be Fold/Raise, not limp/call.

export const CASH_GAME_BASELINE = {
  game: "No-limit Texas Hold'em cash",
  tableDefault: "6-max unless stated",
  stackBB: 100,
  noAntes: true,
  note: "Use explicit action text for every preflop spot: folded to hero, facing an open, or facing a 3-bet.",
};


export const HAND_QUIZ = [
  {
    cards: [["A","♠"],["A","♥"],["A","♦"],["7","♣"],["3","♠"]],
    answer: "Three of a Kind",
    options: ["Three of a Kind", "Two Pair", "Full House", "Four of a Kind"],
    explain: "Three aces with no pair to make a full house. This is 'trips' (or a 'set' if your aces came from a pocket pair).",
  },
  {
    cards: [["K","♥"],["Q","♥"],["J","♥"],["10","♥"],["9","♥"]],
    answer: "Straight Flush",
    options: ["Royal Flush", "Straight Flush", "Flush", "Straight"],
    explain: "Five consecutive hearts — but it's not a Royal Flush because that requires A-K-Q-J-10 specifically.",
  },
  {
    cards: [["8","♠"],["8","♥"],["K","♦"],["K","♣"],["3","♠"]],
    answer: "Two Pair",
    options: ["Two Pair", "Three of a Kind", "Full House", "One Pair"],
    explain: "Kings and eights. You'd describe this as 'two pair, kings and eights' — the higher pair is named first.",
  },
  {
    cards: [["A","♣"],["K","♣"],["Q","♣"],["J","♣"],["10","♣"]],
    answer: "Royal Flush",
    options: ["Royal Flush", "Straight Flush", "Flush", "Five of a Kind"],
    explain: "The unbeatable hand. A-K-Q-J-10 of the same suit. You'll see one roughly once every 650,000 hands.",
  },
  {
    cards: [["7","♠"],["7","♥"],["7","♦"],["2","♣"],["2","♠"]],
    answer: "Full House",
    options: ["Full House", "Three of a Kind", "Two Pair", "Four of a Kind"],
    explain: "Three sevens plus a pair of twos. Spoken as 'sevens full of twos.' Ranked by the trips.",
  },
  {
    cards: [["5","♠"],["4","♥"],["3","♦"],["2","♣"],["A","♠"]],
    answer: "Straight",
    options: ["Straight", "Straight Flush", "High Card", "Flush"],
    explain: "The 'wheel' — A-2-3-4-5, where the ace plays low. It's the lowest possible straight.",
  },
  {
    cards: [["9","♣"],["9","♠"],["9","♥"],["9","♦"],["K","♣"]],
    answer: "Four of a Kind",
    options: ["Four of a Kind", "Full House", "Three of a Kind", "Straight Flush"],
    explain: "Quad nines with a king kicker. 'Quads' beat anything except a straight flush or royal flush.",
  },
  {
    cards: [["A","♥"],["10","♥"],["7","♥"],["4","♥"],["2","♥"]],
    answer: "Flush",
    options: ["Flush", "Straight Flush", "Royal Flush", "High Card"],
    explain: "Five hearts but not in sequence — that's a flush, ace-high. Beats any straight, loses to a full house.",
  },
  {
    cards: [["Q","♠"],["J","♥"],["10","♦"],["9","♣"],["8","♠"]],
    answer: "Straight",
    options: ["Straight", "Straight Flush", "High Card", "Three of a Kind"],
    explain: "Q-J-10-9-8, mixed suits. Queen-high straight. The suits being different is what makes it a straight rather than a straight flush.",
  },
  {
    cards: [["6","♠"],["6","♦"],["3","♣"],["3","♥"],["3","♠"]],
    answer: "Full House",
    options: ["Full House", "Two Pair", "Three of a Kind", "Four of a Kind"],
    explain: "Threes full of sixes. Note: it's named by the trips first ('threes full'), not by which pair is higher.",
  },
  {
    cards: [["A","♦"],["K","♥"],["Q","♠"],["10","♣"],["7","♦"]],
    answer: "High Card",
    options: ["High Card", "One Pair", "Straight", "Flush"],
    explain: "No pair, no straight (missing the jack), no flush. Ace-high. About a third of all dealt hands end up here.",
  },
  {
    cards: [["J","♣"],["J","♦"],["J","♠"],["A","♥"],["K","♦"]],
    answer: "Three of a Kind",
    options: ["Three of a Kind", "Two Pair", "Full House", "Straight"],
    explain: "Trip jacks with A-K kickers. Strong hand, but watch for full houses on paired boards.",
  },
  {
    cards: [["A","♠"],["A","♣"],["K","♥"],["K","♦"],["Q","♠"]],
    answer: "Two Pair",
    options: ["Two Pair", "Three of a Kind", "Full House", "Four of a Kind"],
    explain: "Aces and kings — the strongest two pair possible. Often called 'two pair, aces up.'",
  },
  {
    cards: [["10","♠"],["10","♥"],["6","♣"],["4","♦"],["2","♠"]],
    answer: "One Pair",
    options: ["One Pair", "Two Pair", "Three of a Kind", "High Card"],
    explain: "Pair of tens with junk kickers. A common holding — often the winner in unpaired-board pots.",
  },
  {
    cards: [["A","♣"],["2","♣"],["3","♣"],["4","♣"],["5","♣"]],
    answer: "Straight Flush",
    options: ["Straight Flush", "Royal Flush", "Flush", "Straight"],
    explain: "The 'steel wheel' — 5-high straight flush. Lowest straight flush possible, but still crushes regular flushes.",
  },
  {
    cards: [["K","♠"],["K","♣"],["K","♥"],["K","♦"],["A","♠"]],
    answer: "Four of a Kind",
    options: ["Four of a Kind", "Full House", "Royal Flush", "Three of a Kind"],
    explain: "Quad kings with the ace kicker. Only quad aces and any straight/royal flush beat this.",
  },
  {
    cards: [["7","♥"],["6","♥"],["5","♣"],["4","♦"],["3","♠"]],
    answer: "Straight",
    options: ["Straight", "Straight Flush", "Flush", "High Card"],
    explain: "7-6-5-4-3 with mixed suits. Seven-high straight. Don't be fooled by the two hearts — flushes need five of a suit.",
  },
  {
    cards: [["Q","♦"],["Q","♥"],["Q","♣"],["Q","♠"],["3","♥"]],
    answer: "Four of a Kind",
    options: ["Four of a Kind", "Full House", "Three of a Kind", "Straight Flush"],
    explain: "Quad queens. The kicker (3) only matters if another player also has quad queens — which can't happen with the same four cards in a community-card game, but matters in stud-style games.",
  },
  {
    cards: [["8","♦"],["6","♦"],["4","♦"],["2","♦"],["A","♦"]],
    answer: "Flush",
    options: ["Flush", "Straight Flush", "Two Pair", "High Card"],
    explain: "Five diamonds, ace-high. Not a straight (gaps everywhere), but a strong flush. Note that it's not a 'royal flush' — that requires A-K-Q-J-10 specifically.",
  },
  {
    cards: [["5","♣"],["5","♦"],["5","♥"],["8","♠"],["8","♣"]],
    answer: "Full House",
    options: ["Full House", "Three of a Kind", "Two Pair", "Four of a Kind"],
    explain: "Fives full of eights. Even though the eights are higher, the trips determine the rank — 5s full beats any 4s full but loses to any 6s full.",
  },
];

export const WINNING_HAND_QUIZ = [
  {
    flop: [["K","♠"],["7","♦"],["2","♣"]],
    turn: ["3","♠"], river: ["J","♥"],
    handA: [["A","♥"],["K","♣"]],
    handB: [["7","♥"],["7","♣"]],
    explain: "A flopped set rarely loses. Sevens hit a set on the flop and the runout was bricks — no straight or flush gets there. Top pair top kicker pays off the whole way.",
  },
  {
    flop: [["Q","♥"],["J","♥"],["10","♥"]],
    turn: ["2","♣"], river: ["5","♦"],
    handA: [["A","♥"],["K","♣"]],
    handB: [["9","♥"],["8","♣"]],
    explain: "Both made straights on the flop — A-K-Q-J-10 (Broadway) vs Q-J-10-9-8. The higher straight wins. Note Hand A also has the Ace of hearts, but with only three hearts on the board, no flush is possible.",
  },
  {
    flop: [["A","♠"],["A","♥"],["K","♦"]],
    turn: ["3","♣"], river: ["7","♦"],
    handA: [["A","♣"],["Q","♥"]],
    handB: [["K","♠"],["K","♣"]],
    explain: "Pocket kings turned into kings full of aces — beating trip aces with a queen kicker. When the board has two pairs available (or a pair plus your set), the full house emerges. Boat beats trips.",
  },
  {
    flop: [["9","♣"],["8","♣"],["2","♣"]],
    turn: ["K","♥"], river: ["4","♦"],
    handA: [["A","♣"],["5","♦"]],
    handB: [["10","♥"],["7","♥"]],
    explain: "The nut flush was made on the flop — Hand A had one club and the board brought three. Hand B had open-ended straight outs but the turn (K) and river (4) bricked. Made hands beat broken draws every time.",
  },
  {
    flop: [["Q","♦"],["Q","♣"],["5","♥"]],
    turn: ["8","♠"], river: ["3","♦"],
    handA: [["Q","♥"],["5","♠"]],
    handB: [["A","♥"],["A","♣"]],
    explain: "The board paired queens, and Hand A had Q-5 — flopping queens full of fives. Pocket aces flopped two pair (aces and queens) but never improved. The full house wins. Aces aren't invincible on paired boards.",
  },
  {
    flop: [["J","♠"],["J","♦"],["J","♣"]],
    turn: ["7","♥"], river: ["2","♣"],
    handA: [["A","♥"],["K","♥"]],
    handB: [["10","♣"],["10","♦"]],
    explain: "Trips on the board makes any pocket pair into a full house. Pocket tens become jacks-full-of-tens — beating trip jacks with the A-K kicker. When the board shows three of a kind, every pocket pair is gold.",
  },
  {
    flop: [["8","♥"],["7","♠"],["6","♦"]],
    turn: ["A","♠"], river: ["K","♦"],
    handA: [["9","♣"],["5","♦"]],
    handB: [["10","♥"],["9","♥"]],
    explain: "Both flopped straights. Hand A: 9-8-7-6-5. Hand B: 10-9-8-7-6. Higher straight wins. The turn and river were bricks — neither helped or hurt.",
  },
  {
    flop: [["K","♥"],["10","♥"],["3","♣"]],
    turn: ["7","♦"], river: ["2","♠"],
    handA: [["K","♣"],["Q","♦"]],
    handB: [["10","♣"],["10","♦"]],
    explain: "Top pair top kicker vs a flopped set. The runout was dry — no flush, no straight to bail Hand A out. Sets are the silent killers of poker; opponents almost never see them coming.",
  },
  {
    flop: [["A","♠"],["K","♠"],["Q","♠"]],
    turn: ["7","♦"], river: ["3","♣"],
    handA: [["J","♠"],["10","♠"]],
    handB: [["A","♥"],["A","♦"]],
    explain: "Royal flush vs trip aces. The flop already had it locked — A-K-Q-J-10 of spades. Trip aces is a hand most players go broke with; here, against the ultimate hand, it's drawing dead from the flop.",
  },
  {
    flop: [["6","♦"],["6","♥"],["6","♣"]],
    turn: ["A","♠"], river: ["K","♥"],
    handA: [["A","♥"],["A","♠"]],
    handB: [["6","♠"],["2","♣"]],
    explain: "Quad sixes vs aces full. The board flopped trip sixes — a wild flop. The case six in Hand B made quads. Hand A turned aces full but quads still win. Note: if Hand B held T-2 instead, quads would still win on the strength of the four sixes.",
  },
  {
    flop: [["7","♥"],["5","♦"],["3","♠"]],
    turn: ["K","♣"], river: ["2","♦"],
    handA: [["A","♣"],["A","♥"]],
    handB: [["6","♦"],["4","♣"]],
    explain: "Pocket aces flopped an overpair. Hand B flopped a 7-high straight (7-6-5-4-3) — already ahead. The turn and river didn't pair the board, so no full house redemption for A. Read texture; small connected boards crush overpairs.",
  },
  {
    flop: [["10","♣"],["9","♣"],["8","♣"]],
    turn: ["2","♦"], river: ["K","♠"],
    handA: [["J","♣"],["7","♣"]],
    handB: [["A","♣"],["K","♦"]],
    explain: "Hand A flopped a straight flush — J-10-9-8-7 of clubs. Hand B had the nut flush draw with the Ace of clubs but only ever had four clubs. The river K paired top but it didn't matter — straight flush is a near-unbeatable hand.",
  },
  {
    flop: [["A","♠"],["K","♥"],["7","♦"]],
    turn: ["4","♣"], river: ["2","♠"],
    handA: [["A","♣"],["J","♥"]],
    handB: [["A","♦"],["10","♦"]],
    explain: "Both have aces with a king playing from the board, so it comes down to kicker. Jack outranks ten. The runout never paired or made anyone two pair, so kickers decide it. This is exactly why Ace-Jack vs Ace-Ten matters.",
  },
  {
    flop: [["Q","♠"],["Q","♥"],["7","♦"]],
    turn: ["3","♣"], river: ["8","♥"],
    handA: [["Q","♦"],["A","♣"]],
    handB: [["7","♥"],["7","♣"]],
    explain: "Trips with the ace kicker vs a flopped underset that became sevens-full-of-queens. The board paired queens, the underpair pair makes the full house. Set-on-paired-board crushes trips every time.",
  },
  {
    flop: [["8","♥"],["8","♦"],["3","♣"]],
    turn: ["10","♦"], river: ["K","♠"],
    handA: [["A","♠"],["8","♣"]],
    handB: [["3","♥"],["3","♠"]],
    explain: "Trips with ace kicker vs underset that boats up. Threes full of eights wins. Notice both players were ahead of pocket aces here — paired-board flops with multiple players in is a classic trap for overpairs.",
  },
  {
    flop: [["K","♦"],["K","♠"],["K","♥"]],
    turn: ["A","♣"], river: ["2","♥"],
    handA: [["A","♦"],["K","♣"]],
    handB: [["A","♥"],["A","♠"]],
    explain: "Quad kings vs aces full of kings. Both monsters. The case king + ace makes quads. Pocket aces fill up to the second-best full house... and lose. This is the kind of hand that defines a player's career.",
  },
  {
    flop: [["J","♥"],["J","♠"],["6","♦"]],
    turn: ["8","♣"], river: ["6","♣"],
    handA: [["A","♣"],["J","♦"]],
    handB: [["6","♥"],["8","♥"]],
    explain: "Hand A had trip jacks the whole way. Hand B had bottom pair on the flop, then turned middle pair (8s and 6s), then RIVERED 6s full of jacks. The river card was a one-outer for the boat. Brutal.",
  },
  {
    flop: [["A","♥"],["10","♥"],["5","♣"]],
    turn: ["K","♥"], river: ["2","♥"],
    handA: [["A","♣"],["A","♠"]],
    handB: [["7","♥"],["6","♥"]],
    explain: "Pocket aces flopped a set of aces — looks unbeatable. But four hearts came on the board (Ah, Th, Kh, 2h), and Hand B has 7h-6h. With six total hearts available, Hand B plays the five highest: Ah-Kh-Th-7h-6h — an ace-high flush (using the board's Ah). Set of aces loses to a four-flush board when you don't hold the right suit.",
  },
  {
    flop: [["9","♥"],["8","♥"],["2","♦"]],
    turn: ["7","♥"], river: ["6","♥"],
    handA: [["A","♥"],["K","♦"]],
    handB: [["10","♣"],["9","♣"]],
    explain: "The runout brings four hearts. Hand A has the Ace of hearts — playing the nut flush. Hand B has 10-9-8-7-6, a ten-high straight from their pocket ten + the board. Flush beats straight. Hand A wins with ace-high flush.",
  },
  {
    flop: [["K","♥"],["Q","♦"],["3","♠"]],
    turn: ["J","♣"], river: ["10","♥"],
    handA: [["A","♥"],["A","♠"]],
    handB: [["9","♣"],["9","♦"]],
    explain: "Pocket aces and pocket nines both started as overpair / underpair. The board ran out K-Q-J-10 — meaning anyone with an Ace makes Broadway (A-K-Q-J-10), and anyone with a 9 makes a 9-high straight. Hand A's ace plays as A-K-Q-J-10. Hand B plays K-Q-J-10-9. Both straights, but Hand A's Broadway is the nuts.",
  },
  {
    flop: [["7","♣"],["7","♦"],["2","♥"]],
    turn: ["A","♠"], river: ["A","♣"],
    handA: [["A","♥"],["K","♥"]],
    handB: [["7","♥"],["7","♠"]],
    explain: "Quads vs aces full! The board double-paired (sevens flop, aces turn+river). Hand B had pocket sevens — quad sevens by the river. Hand A turned trip aces, rivered four-of-a-kind on the board... wait, with one ace in hand and two on the board plus the trips on the board, that's a full house: aces full of sevens. Quads still win.",
  },
  {
    flop: [["10","♠"],["10","♥"],["10","♦"]],
    turn: ["K","♠"], river: ["K","♦"],
    handA: [["K","♣"],["Q","♥"]],
    handB: [["A","♠"],["J","♠"]],
    explain: "The board ran out 10-10-10-K-K — already a full house by itself (tens full of kings). Hand A has K-Q: combining with the trip tens and the board kings makes K-K-K-10-10, kings full of tens. Hand B's A-J doesn't pair anything on the board, so they just play the board (10-10-10-K-K) — tens full of kings. Higher trips in the boat wins. Hand A by a single card.",
  },
  {
    flop: [["Q","♥"],["Q","♦"],["5","♣"]],
    turn: ["5","♥"], river: ["A","♠"],
    handA: [["A","♣"],["Q","♣"]],
    handB: [["A","♥"],["5","♦"]],
    explain: "Hand A flopped trip queens with the ace kicker. The river paired aces — but Hand A holds Ac! That makes Q-Q-Q-A-A: queens full of aces. Hand B (A-5) had two pair (As and 5s) on the river, but their best full house option is 5-5-5-A-A (using the trip 5s once the turn paired). Both players have a boat 'full of aces,' but queens-full beats fives-full. Higher trips wins the boat war.",
  },
  {
    flop: [["8","♠"],["7","♠"],["6","♠"]],
    turn: ["5","♠"], river: ["9","♠"],
    handA: [["A","♠"],["2","♥"]],
    handB: [["10","♠"],["J","♣"]],
    explain: "The board is five spades in sequence: 9-8-7-6-5 — already a straight flush. Both players play the board for at least a 9-high straight flush. Hand B has the 10 of spades, which extends the straight flush to 10-high (10-9-8-7-6). Hand A's Ace of spades doesn't help — A-2 leaves a gap, so A is stuck with the board's 9-high straight flush. Higher straight flush wins.",
  },
  {
    flop: [["A","♥"],["K","♥"],["Q","♣"]],
    turn: ["10","♣"], river: ["J","♦"],
    handA: [["10","♥"],["10","♦"]],
    handB: [["9","♣"],["8","♣"]],
    explain: "The river J completes Broadway on the board (A-K-Q-J-10). Hand A had a set of tens through the turn, then plays the board for Broadway on the river (the set is irrelevant — A-K-Q-J-10 is higher). Hand B's 9-8 makes nothing — they play A-K-Q-J-10 from the board. Both players play the board for Broadway: it's a chopped pot. TIE!",
    isTie: true,
  },
  {
    flop: [["6","♦"],["7","♥"],["8","♠"]],
    turn: ["9","♣"], river: ["10","♥"],
    handA: [["5","♣"],["4","♦"]],
    handB: [["J","♠"],["2","♣"]],
    explain: "The board itself contains 6-7-8-9-10 — a 10-high straight. Hand A's 5-4 doesn't play (their 6-7-8-9-10 straight is just the board; no improvement). Hand B's Jack makes J-10-9-8-7 — Jack-high straight. J-high beats 10-high. Hand B wins with the higher straight using just one card.",
  },
];

export const PREFLOP_QUIZ = [
  {
    pos: "UTG", cards: [["A","♠"],["A","♥"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Pocket aces are the strongest preflop hand. Always raise for value — never slow-play from early position. You want to build the pot and thin the field.",
  },
  {
    pos: "UTG", cards: [["K","♥"],["7","♣"]],
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "Offsuit K-7 is a trap from UTG. You're dominated by KQ, KJ, KT, AK, and you have eight players left to act. Easy fold.",
  },
  {
    pos: "BTN", cards: [["A","♣"],["5","♣"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Suited ace on the button — open it. You have position post-flop, the wheel-draw potential, nut-flush potential, and you can steal the blinds.",
  },
  {
    pos: "MP", cards: [["7","♥"],["2","♦"]],
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "Statistically the worst hand in Hold'em. No straight potential, offsuit, dominated by basically everything. Fold from any position.",
  },
  {
    spotType: "Facing Open",
    table: "6-max cash",
    stackBB: 100,
    pos: "BB", cards: [["Q","♠"],["Q","♦"]],
    prompt: "Button opens to 2.5bb. You are in the big blind with Q♠Q♦. Best action?",
    answer: "3-bet",
    options: ["Fold", "Call", "3-bet"],
    explain: "Pocket queens are a premium hand and a clear value 3-bet versus a button open. Calling can exist in some slow-play mixes, but the clean default is to re-raise for value and deny equity.",
  },
  {
    pos: "CO", cards: [["J","♠"],["10","♠"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Suited connectors from the cutoff are a clear open. Strong straight and flush potential, plus you have position on most opponents post-flop.",
  },
  {
    pos: "SB", cards: [["9","♣"],["3","♥"]],
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "From the SB you'll always be out of position post-flop. Junk hands like 9-3 offsuit lose money even getting in cheap. The half-blind isn't a discount worth taking.",
  },
  {
    pos: "UTG", cards: [["K","♠"],["K","♦"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Pocket kings — the second-strongest starting hand. Raise for value from anywhere. Don't get cute trying to trap; build the pot now.",
  },
  {
    pos: "HJ", cards: [["A","♥"],["Q","♥"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Suited A-Q is premium. Open-raise from the hijack to build a pot in position with a strong, high-equity hand that flops well.",
  },
  {
    pos: "MP", cards: [["8","♦"],["8","♣"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Pocket eights from middle position are an open-raise. Against tighter ranges from EP/MP, raise; against wider ranges (button), still raise. Set-mining hand with showdown value.",
  },
  {
    pos: "BTN", cards: [["6","♥"],["5","♥"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Suited connectors on the button are a steal-and-play hand. Position lets you c-bet bluff, hit disguised straights/flushes, and pick up blinds when folded around.",
  },
  {
    pos: "CO", cards: [["A","♦"],["10","♣"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "A-T offsuit from the cutoff is a comfortable open. Watch out for getting 3-bet from the button or blinds — A-T offsuit doesn't love facing big resistance.",
  },
  {
    pos: "UTG", cards: [["A","♠"],["J","♦"]],
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "A-J offsuit is a famously trappy hand from UTG in tougher games. It's dominated by A-K, A-Q, and pocket pairs JJ+. In a tight 9-handed game, fold it. (Looser games: open it.)",
  },
  {
    spotType: "Facing Open",
    table: "6-max cash",
    stackBB: 100,
    pos: "SB", cards: [["A","♥"],["A","♦"]],
    prompt: "Button opens to 2.5bb. You are in the small blind with A♥A♦. Best action?",
    answer: "3-bet",
    options: ["Fold", "Call", "3-bet"],
    explain: "Pocket aces are the strongest starting hand. From the small blind facing an open, 3-bet for value. You are out of position post-flop, so building the pot and reducing multiway risk matters.",
  },
  {
    spotType: "Facing Open",
    table: "6-max cash",
    stackBB: 100,
    pos: "BB", cards: [["10","♥"],["9","♣"]],
    prompt: "Button opens to 2.2bb. Small blind folds. You are in the big blind with T♥9♣. Best action?",
    answer: "Call",
    options: ["Fold", "Call", "3-bet"],
    explain: "T9 offsuit is a marginal but reasonable defend versus a small button open. You are getting good pot odds, close the action, and have some straight potential. Versus an early-position open or larger sizing, this becomes a fold much more often.",
  },
  {
    pos: "MP", cards: [["K","♥"],["J","♦"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "K-J offsuit from middle position is a standard open. Strong broadway, makes top pair often. Fold it from UTG in tight games; raise it from MP onwards.",
  },
  {
    spotType: "RFI",
    table: "6-max cash",
    stackBB: 100,
    pos: "UTG", cards: [["6","♣"],["6","♥"]],
    prompt: "Action folds to you UTG with 6♣6♥ at 100bb effective. Best default action?",
    answer: "Raise",
    options: ["Fold", "Raise"],
    explain: "Pocket sixes are a borderline but standard open in many 6-max cash ranges. In tighter full-ring games, folding can be reasonable. Open-limping/calling first-in is not the default strategy.",
  },
  {
    pos: "BTN", cards: [["Q","♦"],["10","♣"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Q-T offsuit from the button: open it. Folded around to you, you should raise about half of all hands. Q-T flops top pair, straights, and steals blinds when missed.",
  },
  {
    pos: "HJ", cards: [["7","♠"],["6","♠"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Suited connectors from the hijack: open. They flop well disguised — straights, flushes, and pair-plus-draw combos. Fold equity plus implied odds make these profitable.",
  },
  {
    pos: "CO", cards: [["3","♣"],["3","♦"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Pocket threes from the cutoff: raise. Against late-position calling ranges, you have set-mining equity and fold equity. Don't limp small pairs in late position.",
  },
  {
    spotType: "Facing Open",
    table: "6-max cash",
    stackBB: 100,
    pos: "SB", cards: [["A","♣"],["K","♣"]],
    prompt: "Cutoff opens to 2.5bb. Button folds. You are in the small blind with A♣K♣. Best action?",
    answer: "3-bet",
    options: ["Fold", "Call", "3-bet"],
    explain: "AK suited is a premium 3-bet from the small blind. Calling can exist in some advanced mixed strategies, but as a default, 3-bet for value and avoid playing a bloated multiway pot out of position.",
  },
  {
    pos: "BB", cards: [["J","♥"],["3","♦"]],
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "Even from the big blind facing a single open, J-3 offsuit is too weak to defend profitably. Defending too wide from the BB bleeds chips. Fold the trash.",
  },
  {
    spotType: "RFI",
    table: "6-max cash",
    stackBB: 100,
    pos: "UTG", cards: [["Q","♥"],["J","♥"]],
    prompt: "Action folds to you UTG with Q♥J♥ at 100bb effective. Best default action?",
    answer: "Raise",
    options: ["Fold", "Raise"],
    explain: "QJs is a borderline but playable UTG open in many 6-max cash ranges because it is suited, connected, and has broadway value. In tighter full-ring games, folding is reasonable. Calling first-in is not a strong default.",
  },
  {
    spotType: "RFI",
    table: "6-max cash",
    stackBB: 100,
    pos: "BTN", cards: [["2","♦"],["2","♥"]],
    prompt: "Action folds to you on the button with 2♦2♥ at 100bb effective. Best action?",
    answer: "Raise",
    options: ["Fold", "Raise"],
    explain: "Any pocket pair is usually opened from the button when folded to. You gain fold equity, have position post-flop, and can still flop sets. This is not the same as facing an early-position open.",
  },
  {
    pos: "CO", cards: [["K","♦"],["10","♥"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "K-T offsuit from the cutoff is a clear open. Strong broadway with showdown value. Fold to a 3-bet from the BB — they have all the AK and big pairs.",
  },
  {
    pos: "MP", cards: [["A","♠"],["7","♦"]],
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "A-7 offsuit from middle position is too weak. Dominated by every higher ace, and your kicker plays poorly when you flop top pair. Wait for better.",
  },
  {
    pos: "BTN", cards: [["8","♣"],["7","♣"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Suited connectors on the button — raise every time. High equity to flop straight draws, flush draws, two pair, sets, and combo draws. The button's bread-and-butter speculative hand.",
  },
  {
    pos: "UTG", cards: [["10","♠"],["10","♦"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Pocket tens from UTG: raise. Don't get fancy. You have a top-15 starting hand; play it straightforwardly. If you get 4-bet, you can usually fold, but for now: raise.",
  },
  {
    spotType: "Facing Open",
    table: "6-max cash",
    stackBB: 100,
    pos: "BB", cards: [["K","♥"],["Q","♦"]],
    prompt: "Button opens to 2.5bb. Small blind folds. You are in the big blind with K♥Q♦. Best aggressive default?",
    answer: "3-bet",
    options: ["Fold", "Call", "3-bet"],
    explain: "KQo is strong enough to continue versus a button open. Calling is standard in many ranges, but 3-betting is a good aggressive default against wide late-position opens because it gains initiative, denies equity, and gets value from worse broadways.",
  },
  {
    pos: "HJ", cards: [["9","♥"],["9","♦"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Pocket nines from the hijack: raise. Solid pair, set-mining equity, and you have position over MP and the blinds. Fold to a tight UTG 3-bet.",
  },
  {
    pos: "SB", cards: [["Q","♣"],["10","♥"]],
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "Q-T offsuit from the small blind facing an open: fold. You'll be out of position the rest of the hand, and Q-T offsuit is too weak to 3-bet for value. Don't get talked into 'half-pricing.'",
  },
  {
    pos: "CO", cards: [["5","♥"],["5","♦"]],
    answer: "Raise",
    options: ["Fold", "Call", "Raise"],
    explain: "Pocket fives from the cutoff: raise. Set-mining hand with showdown value. Open small in tight games to keep your range balanced; standard size in normal games.",
  },
  {
    pos: "BTN", cards: [["A","♠"],["K","♣"]],
    prompt: "UTG opens to 2.5bb. Folds to you on the button with A-K offsuit at 100bb effective. Best action?",
    answer: "3-bet",
    options: ["Fold", "Call", "3-bet"],
    explain: "A-K offsuit is a high-frequency value 3-bet versus UTG. It dominates portions of continuing ranges and benefits from initiative.",
  },
  {
    pos: "BB", cards: [["K","♠"],["9","♠"]],
    prompt: "Cutoff opens min-raise to 2bb. You are in the big blind with K-9 suited, 100bb deep. Decision?",
    answer: "Call",
    options: ["Fold", "Call", "3-bet"],
    explain: "K9s defends well versus late opens because of pot odds and playability. Calling is standard; 3-bet mix is acceptable versus weak players.",
  },
  {
    pos: "SB", cards: [["A","♣"],["5","♣"]],
    prompt: "Button opens to 2.2bb. You are in the small blind with A-5 suited. Best default line?",
    answer: "3-bet",
    options: ["Fold", "Call", "3-bet"],
    explain: "A5s is a classic small-blind 3-bet candidate: blocker value, wheel potential, and it avoids weak out-of-position flats.",
  },
  {
    pos: "CO", cards: [["Q","♣"],["J","♦"]],
    prompt: "UTG opens to 3bb and action folds to you in cutoff with Q-J offsuit. What is best in most live pools?",
    answer: "Fold",
    options: ["Fold", "Call", "3-bet"],
    explain: "QJo performs poorly versus strong early-position ranges and creates dominated top-pair spots. Folding is disciplined and profitable long term.",
  },
  {
    pos: "BTN", cards: [["7","♠"],["6","♠"]],
    prompt: "Hijack opens 2.5bb. You're on the button with 7-6 suited and both blinds are straightforward. Action?",
    answer: "Call",
    options: ["Fold", "Call", "3-bet"],
    explain: "Button call is standard: suited connectors realize equity well in position and can win large pots when they connect hard.",
  },
  {
    pos: "HJ", cards: [["Q","♠"],["Q","♥"]],
    prompt: "You open HJ to 2.5bb with QQ. CO 3-bets to 8.5bb, others fold. Best baseline response at 100bb?",
    answer: "4-bet",
    options: ["Fold", "Call", "4-bet"],
    explain: "QQ is too strong to fold and usually wants to 4-bet for value/protection against aggressive cutoff 3-bet ranges.",
  },
  {
    pos: "BB", cards: [["A","♣"],["J","♣"]],
    prompt: "Button opens 2.2bb. You are in BB with A-J suited. Preferred action?",
    answer: "3-bet",
    options: ["Fold", "Call", "3-bet"],
    explain: "AJs is ahead of many button opens and benefits from denying equity. 3-betting captures value and simplifies many runouts.",
  },
];

export const POSTFLOP_QUIZ = [
  {
    hole: [["A","♠"],["K","♠"]], board: [["Q","♠"],["7","♠"],["3","♥"]],
    pot: 60, toCall: 30,
    prompt: "You hold A-K of spades. Flop comes Q-7♠-3♥. Opponent bets half-pot. What's your move?",
    answer: "Call/Raise",
    options: ["Fold", "Call/Raise", "Min-raise only"],
    explain: "You have the nut flush draw plus two overcards, although the overcard outs are not always clean. Versus a half-pot bet, this is a clear continue. Calling is standard; raising can be used as a semi-bluff because it adds fold equity.",
  },
  {
    hole: [["10","♥"],["10","♦"]], board: [["A","♣"],["K","♠"],["7","♥"]],
    pot: 80, toCall: 60,
    prompt: "You have pocket tens. Flop is A-K-7 rainbow. Aggressive opponent leads big into you. Decision?",
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "Two overcards on the flop is the worst-case scenario for an underpair. You're getting 2.3-to-1 but realistically have 2 outs (8% to hit a set). Against a player betting big into a coordinated board, fold and save your stack.",
  },
  {
    hole: [["J","♣"],["10","♣"]], board: [["9","♣"],["8","♣"],["2","♥"]],
    pot: 50, toCall: 0,
    prompt: "You have J-10 of clubs. Flop is 9♣-8♣-2♥. You're first to act. What's the play?",
    answer: "Bet",
    options: ["Check", "Bet", "Check-fold"],
    explain: "This is a monster combo draw: open-ended straight draw, flush draw, straight-flush potential, and some overcard value. You have around 15 primary draw outs before considering overcards. Betting as a semi-bluff is strong because you can win immediately or build a pot when you improve.",
  },
  {
    hole: [["A","♥"],["A","♦"]], board: [["9","♣"],["8","♣"],["7","♣"]],
    pot: 100, toCall: 80,
    prompt: "Pocket aces. Flop is 9-8-7 all clubs. Opponent shoves. Your aces are red. What now?",
    answer: "Fold",
    options: ["Fold", "Call", "Snap-call"],
    explain: "A wet board and a shove put your red aces in a bad spot. You lose to made flushes, straights, sets, two pair, and huge combo draws, and you have no club redraw. Unless villain is wildly over-bluffing, folding is the disciplined default.",
  },
  {
    hole: [["K","♠"],["Q","♥"]], board: [["K","♦"],["7","♣"],["2","♠"]],
    pot: 40, toCall: 0,
    prompt: "K-Q offsuit. Flop K-7-2 rainbow. You raised preflop and got one caller. They check to you. What's your action?",
    answer: "Bet",
    options: ["Check", "Bet", "Check-raise plan"],
    explain: "Top pair, strong kicker, dry board. You should c-bet for value and protection. Check gives free cards to underpairs and overcards on later streets. Bet around 1/2 to 2/3 pot.",
  },
  {
    hole: [["7","♦"],["7","♥"]], board: [["7","♠"],["K","♣"],["2","♥"]],
    pot: 30, toCall: 0,
    prompt: "Pocket sevens. Flop comes 7-K-2 rainbow. You raised preflop, got two callers, and you're first to act. Action?",
    answer: "Bet",
    options: ["Check", "Bet", "Slow-play"],
    explain: "Bottom set on a dry board with two opponents — bet for value. Slow-playing leaks value here; nothing scary is coming, and someone has a king they'll pay you off with. Build the pot now.",
  },
  {
    hole: [["A","♣"],["Q","♣"]], board: [["J","♥"],["8","♦"],["3","♣"]],
    pot: 24, toCall: 0,
    prompt: "A-Q suited. Flop J-8-3 rainbow. You raised preflop, BB called. They check. What's the standard play?",
    answer: "Bet",
    options: ["Check", "Bet", "Big bet"],
    explain: "Standard c-bet spot. Even though you missed, the board hits your range better than the BB's calling range. Bet around 1/3 pot — get folds from underpairs and air, give up cheap if check-raised.",
  },
  {
    hole: [["Q","♥"],["Q","♦"]], board: [["A","♠"],["10","♥"],["6","♦"]],
    pot: 60, toCall: 40,
    prompt: "Pocket queens. Flop A-10-6 rainbow. Tight opponent leads 2/3 pot into you. Decision?",
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "An ace-high flop and a tight opponent leading into a multi-way pot is a classic 'one-pair trap.' QQ is now a bluff catcher with 2 outs to a set. Against tight bettors who don't bluff enough, fold.",
  },
  {
    hole: [["6","♥"],["5","♥"]], board: [["7","♥"],["8","♥"],["K","♣"]],
    pot: 40, toCall: 30,
    prompt: "6-5 of hearts. Flop 7♥-8♥-K♣. Opponent bets 3/4 pot. What's the play?",
    answer: "Call",
    options: ["Fold", "Call", "Raise"],
    explain: "You have a flush draw (9 outs) AND an open-ended straight draw (8 outs, but 2 overlap with flush) = 15 clean outs. About 54% equity to make a hand by the river. Easy call. Raising also fine, but call works.",
  },
  {
    hole: [["A","♦"],["8","♦"]], board: [["K","♦"],["7","♦"],["4","♦"]],
    pot: 50, toCall: 35,
    prompt: "A-8 of diamonds. Flop is K-7-4 all diamonds. Opponent leads big. Decision?",
    answer: "Call",
    options: ["Fold", "Call", "Raise"],
    explain: "You have the nut flush already. Calling is a strong trap line, especially in position, because it keeps bluffs and worse value hands in. Raising is also viable against players who will continue with worse flushes, sets, or strong Kx with a diamond.",
  },
  {
    hole: [["10","♠"],["9","♠"]], board: [["J","♦"],["8","♣"],["2","♥"]],
    pot: 30, toCall: 20,
    prompt: "10-9 suited. Flop is J-8-2 rainbow. Opponent bets 2/3 pot. What's the play?",
    answer: "Call",
    options: ["Fold", "Call", "Raise"],
    explain: "Open-ended straight draw — 8 outs, about 32% by river. Pot odds give you ~28% needed. With implied odds (you'll get paid when you hit), this is a clear call. Don't raise; you have a draw, not a made hand.",
  },
  {
    hole: [["A","♥"],["K","♣"]], board: [["2","♠"],["7","♦"],["10","♣"]],
    pot: 40, toCall: 0,
    prompt: "A-K offsuit, you raised preflop. Flop comes 2-7-10 rainbow. BB checks to you. Standard play?",
    answer: "Bet",
    options: ["Check", "Bet", "Check-raise plan"],
    explain: "Standard small c-bet. The board misses BB's calling range often. Bet 1/3 pot to fold out underpairs and air, while leaving yourself easy give-up if check-raised. AK has 6 outs to overcards even if called.",
  },
  {
    hole: [["8","♠"],["8","♣"]], board: [["A","♦"],["A","♣"],["6","♥"]],
    pot: 30, toCall: 22,
    prompt: "Pocket eights. Flop comes A-A-6. Opponent leads 2/3 pot. Decision?",
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "Paired ace board is the worst for underpairs. They have an ace, a bigger pocket pair, or are bluffing — but folding ranges hit one of those two more often than the bluff. Fold and move on.",
  },
  {
    hole: [["K","♦"],["Q","♦"]], board: [["10","♦"],["9","♦"],["3","♣"]],
    pot: 24, toCall: 0,
    prompt: "K-Q of diamonds. Flop is 10♦-9♦-3♣. You're in position vs one caller. They check. Action?",
    answer: "Bet",
    options: ["Check", "Bet", "Check-raise plan"],
    explain: "Massive equity hand — flush draw + gutshot + two overcards. 14+ outs, about 55% equity. Bet for the semi-bluff: you fold out weak hands, build the pot for when you hit, and gain initiative.",
  },
  {
    hole: [["9","♦"],["9","♣"]], board: [["Q","♥"],["J","♠"],["10","♦"]],
    pot: 40, toCall: 30,
    prompt: "Pocket nines. Flop is Q-J-10 rainbow. Opponent bets 3/4 pot. What's the play?",
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "Three Broadway cards on the flop is brutal for an underpair. Anyone with K, 9, or any pocket pair JJ+ is ahead. Plus there's only one card to give you a straight (anything but K is bad). Fold.",
  },
  {
    hole: [["A","♠"],["A","♣"]], board: [["K","♥"],["7","♦"],["2","♠"]],
    pot: 20, toCall: 0,
    prompt: "Pocket aces, you 3-bet preflop. Flop is K-7-2 rainbow. Opponent checks to you. Standard play?",
    answer: "Bet",
    options: ["Check", "Bet", "Check to trap"],
    explain: "Continuation bet for value. Don't slow-play AA on dry boards — your opponent can't catch up easily, and they may have AK paying you off. C-bet around 2/3 pot.",
  },
  {
    hole: [["J","♥"],["J","♦"]], board: [["A","♥"],["A","♣"],["J","♠"]],
    pot: 50, toCall: 35,
    prompt: "Pocket jacks. Flop is A-A-J. Opponent shoves all-in. Decision?",
    answer: "Call",
    options: ["Fold", "Call", "Tank-fold"],
    explain: "Jacks full of aces. The only hands beating you are quad aces (3 combos) and AJ for aces full of jacks (2 combos). Five combos beat you, dozens don't. Snap-call.",
  },
  {
    hole: [["7","♣"],["6","♣"]], board: [["8","♣"],["5","♥"],["2","♦"]],
    pot: 30, toCall: 0,
    prompt: "7-6 of clubs. Flop is 8♣-5-2 rainbow. You called from BB; SB checks to you. Action?",
    answer: "Bet",
    options: ["Check", "Bet", "Massive bet"],
    explain: "Open-ended straight draw + backdoor flush draw. Bet for semi-bluff value. You either fold them out, or build the pot for your draw. Check is fine too, but betting puts maximum pressure on weak made hands.",
  },
  {
    hole: [["K","♣"],["K","♦"]], board: [["A","♠"],["8","♥"],["3","♣"]],
    pot: 40, toCall: 30,
    prompt: "Pocket kings. Flop A-8-3 rainbow. Opponent leads 3/4 pot. What's the play?",
    answer: "Fold",
    options: ["Fold", "Call", "Raise"],
    explain: "When pocket kings see an ace on the flop and an opponent leads big, the math is grim. Most leaders here have an ace. KK is now a 2-out hand. Fold and don't fall in love with your overpair.",
  },
  {
    hole: [["Q","♠"],["J","♠"]], board: [["10","♠"],["9","♠"],["2","♥"]],
    pot: 24, toCall: 0,
    prompt: "Q-J of spades. Flop 10♠-9♠-2♥. Heads-up, opponent checks to you. Action?",
    answer: "Bet",
    options: ["Check", "Bet", "Min-bet"],
    explain: "Flush draw plus open-ended straight draw plus overcards makes this one of the strongest semi-bluff candidates. Not every overcard out is clean, but your equity and fold equity are excellent. Betting is the best default.",

  },
  {
    hole: [["A","♣"],["J","♣"]], board: [["J","♦"],["7","♠"],["2","♣"]],
    pot: 36, toCall: 18,
    prompt: "You open MP with A-J suited. BB check-calls flop J-7-2 rainbow, then leads half-pot on the turn 9♥. Best default?",
    answer: "Call",
    options: ["Fold", "Call", "Raise"],
    explain: "Top pair top kicker should continue against a half-pot donk on a relatively dry texture. Raising isolates against stronger hands; calling keeps dominated Jx and bluffs in.",
  },
  {
    hole: [["K","♠"],["Q","♠"]], board: [["A","♠"],["10","♦"],["4","♠"]],
    pot: 50, toCall: 20,
    prompt: "Flop A♠-10♦-4♠. Opponent c-bets 40% pot. You hold K-Q♠. Best action?",
    answer: "Call",
    options: ["Fold", "Call", "Raise"],
    explain: "Nut-adjacent flush draw plus two overcards yields strong equity and positional flexibility. Calling realizes equity cleanly without inflating variance.",
  },
  {
    hole: [["Q","♦"],["Q","♣"]], board: [["8","♥"],["8","♣"],["4","♠"]],
    pot: 42, toCall: 0,
    prompt: "You 3-bet preflop with QQ and see 8-8-4 rainbow. Villain checks. What is best?",
    answer: "Bet",
    options: ["Check", "Bet", "Overbet"],
    explain: "Paired dry boards favor the aggressor's overpairs. Small to medium c-bet gets value from pocket pairs and denies two overcards.",
  },
  {
    hole: [["A","♥"],["5","♥"]], board: [["K","♥"],["J","♥"],["8","♣"]],
    pot: 48, toCall: 36,
    prompt: "You face a 75% pot bet on K♥-J♥-8♣ with A♥5♥. Decision?",
    answer: "Call",
    options: ["Fold", "Call", "Raise"],
    explain: "Nut flush draw with overcard blocker and backdoor wheel routes has ample equity to continue. Raising can be mixed; call is stable default.",
  },
  {
    hole: [["9","♠"],["9","♥"]], board: [["A","♣"],["9","♦"],["6","♣"]],
    pot: 55, toCall: 0,
    prompt: "Single-raised pot. You flop middle set on A-9-6 two clubs and villain checks. Preferred line?",
    answer: "Bet",
    options: ["Check", "Bet", "Check-back always"],
    explain: "On draw-heavy ace-high boards, set wants value immediately from top pairs and draws. Slow-play allows many bad turn cards.",
  },
  {
    hole: [["K","♣"],["J","♣"]], board: [["Q","♠"],["10","♦"],["3","♥"]],
    pot: 32, toCall: 16,
    prompt: "You hold KJ with open-ended straight draw on Q-10-3 rainbow. Facing half-pot c-bet. Best action?",
    answer: "Call",
    options: ["Fold", "Call", "Raise all-in"],
    explain: "Open-ender has solid direct equity and implied odds. Calling is standard; ripping all-in is unnecessary overplay at deep stacks.",
  },
  {
    hole: [["A","♦"],["Q","♠"]], board: [["Q","♥"],["8","♦"],["5","♠"]],
    pot: 38, toCall: 0,
    prompt: "You c-bet flop with top pair top kicker and get called. Turn is 2♣, villain checks again. Continue?",
    answer: "Bet",
    options: ["Check", "Bet", "Give up"],
    explain: "Blank turn after call still allows value from Qx worse kickers, 8x, and stubborn pairs. A controlled second barrel is standard.",
  },
  {
    hole: [["7","♠"],["7","♣"]], board: [["K","♦"],["Q","♦"],["4","♥"]],
    pot: 44, toCall: 30,
    prompt: "You face a 68% pot c-bet on K-Q-4 with pocket sevens and no diamond. Action?",
    answer: "Fold",
    options: ["Fold", "Call", "Raise bluff"],
    explain: "Underpair with poor backdoors and two overcards is a classic over-defend trap. Without relevant blockers or draws, fold cleanly.",
  },
];

